import type { Coordinate } from "../region-chart/constants";

// Crop/Plant detailed information
export interface CropDetail {
  id: string;
  code: string;
  name: string;
  image: string;
  plantedDate: string;
  seedType: string; // Loại hạt giống
  variety: string; // Giống cây
  groupCropName: string; // Nhóm cây trồng
  notes: string;
  status: "healthy" | "diseased" | "harvesting" | "removed";

  // Location information
  regionId: number;
  regionName: string;
  areaId: number;
  areaName: string;
  plotId: string;
  plotName: string;
  rowNumber?: number; // Số hàng
  coordinate: Coordinate;

  // Growth cycle
  growthStage: string; // Giai đoạn sinh trưởng
  expectedHarvestDate: string;
  actualAge: number; // Tuổi cây (tháng)

  // Certifications
  certifications: Certification[];

  // History
  cultivationHistory: CultivationRecord[];
  diseaseHistory: DiseaseRecord[];
  harvestHistory: HarvestRecord[];
}

export interface Certification {
  id: string;
  name: string;
  issuer: string; // Đơn vị cấp
  issueDate: string;
  expiryDate: string;
  certificateNumber: string;
  status: "valid" | "expired" | "pending";
  documentUrl?: string;
}

export interface CultivationRecord {
  id: string;
  date: string;
  activity: string; // Hoạt động: tưới nước, bón phân, cắt tỉa, etc.
  description: string;
  performedBy: string;
  materials?: string; // Vật tư sử dụng
  quantity?: string;
  cost?: number;
  notes?: string;
}

export interface DiseaseRecord {
  id: string;
  date: string;
  diseaseName: string;
  severity: "low" | "medium" | "high";
  affectedArea: string; // Vùng bị ảnh hưởng
  symptoms: string;
  treatment: string;
  treatmentDate: string;
  recoveryStatus: "recovered" | "treating" | "severe";
  images?: string[];
  notes?: string;
}

export interface HarvestRecord {
  id: string;
  date: string;
  quantity: number; // kg
  quality: "A" | "B" | "C";
  price: number; // VND/kg
  totalRevenue: number;
  buyer?: string;
  notes?: string;
}

// Mock data
export const MOCK_CROPS: CropDetail[] = [
  {
    id: "crop-001",
    code: "SR-RI6-001",
    name: "Sầu riêng Ri6",
    image:
      "https://traicayvuongtron.vn/resources/cache/original_xxxxx/WEBSITE%202023/tim%20hieu%20them/blog/kinh%20nghiem%2Cmeo%20vat/trai%20cay/trai%20cay%20dac%20san/sauriengri6/sauriengri62.jpg.webp",
    plantedDate: "2020-05-15",
    seedType: "Hạt giống F1",
    variety: "Ri6",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây phát triển tốt, đang giai đoạn ra hoa",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Bình Phước Alpha",
    areaId: 1,
    areaName: "Khu vực A - Sầu riêng",
    plotId: "plot-1-1",
    plotName: "Lô A1 - Ri6",
    rowNumber: 3,
    coordinate: { lat: 11.545, lng: 106.895 },

    growthStage: "Ra hoa",
    expectedHarvestDate: "2024-06-15",
    actualAge: 45, // 45 tháng

    certifications: [
      {
        id: "cert-001",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Bình Phước",
        issueDate: "2023-01-10",
        expiryDate: "2025-01-10",
        certificateNumber: "VG-BP-2023-001",
        status: "valid",
      },
      {
        id: "cert-002",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-03-15",
        expiryDate: "2024-03-15",
        certificateNumber: "ORG-VN-2023-045",
        status: "expired",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-001",
        date: "2024-01-15",
        activity: "Bón phân",
        description: "Bón phân NPK 16-16-8",
        performedBy: "Nguyễn Văn A",
        materials: "Phân NPK 16-16-8",
        quantity: "2kg/cây",
        cost: 50000,
        notes: "Thời tiết thuận lợi",
      },
      {
        id: "cult-002",
        date: "2024-01-10",
        activity: "Tưới nước",
        description: "Tưới nhỏ giọt tự động",
        performedBy: "Hệ thống tự động",
        quantity: "50L/cây",
        notes: "Độ ẩm đất 65%",
      },
      {
        id: "cult-003",
        date: "2024-01-05",
        activity: "Cắt tỉa",
        description: "Cắt tỉa cành khô, cành yếu",
        performedBy: "Trần Văn B",
        notes: "Tạo tán cây thông thoáng",
      },
    ],

    diseaseHistory: [
      {
        id: "dis-001",
        date: "2023-11-20",
        diseaseName: "Phytophthora",
        severity: "medium",
        affectedArea: "Thân cây, rễ",
        symptoms: "Thân cây có vết nâu, lá vàng rụng",
        treatment: "Xử lý bằng thuốc Ridomil Gold",
        treatmentDate: "2023-11-21",
        recoveryStatus: "recovered",
        notes: "Đã hồi phục sau 2 tuần",
      },
    ],

    harvestHistory: [
      {
        id: "harv-001",
        date: "2023-08-15",
        quantity: 45,
        quality: "A",
        price: 120000,
        totalRevenue: 5400000,
        buyer: "Công ty TNHH Trái cây Xuất khẩu",
        notes: "Chất lượng tốt, giá cao",
      },
      {
        id: "harv-002",
        date: "2023-02-10",
        quantity: 38,
        quality: "A",
        price: 110000,
        totalRevenue: 4180000,
        buyer: "Chợ đầu mối Bình Điền",
        notes: "Vụ đầu tiên",
      },
    ],
  },
  {
    id: "crop-002",
    code: "LUA-OM-002",
    name: "Lúa OM5451",
    image: "https://giongcamau.vn/uploads/shops/2017_03/om5451-copy.jpg",
    plantedDate: "2023-11-20",
    seedType: "Hạt giống xác nhận",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Cereal & Grain)",
    notes: "Đang giai đoạn chín, sắp thu hoạch",
    status: "harvesting",
    regionId: 2,
    regionName: "Nông trại Hữu cơ Đồng Nai",
    areaId: 3,
    areaName: "Cánh đồng lúa",
    plotId: "plot-2-1",
    plotName: "Lô L1 - OM5451",
    rowNumber: 1,
    coordinate: { lat: 10.963, lng: 107.224 },

    growthStage: "Thu hoạch",
    expectedHarvestDate: "2024-02-01",
    actualAge: 51,

    certifications: [
      {
        id: "cert-003",
        name: "GlobalGAP",
        issuer: "SGS Vietnam",
        issueDate: "2023-06-01",
        expiryDate: "2025-06-01",
        certificateNumber: "GG-VN-2023-089",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-004",
        date: "2024-01-20",
        activity: "Phun thuốc",
        description: "Phun thuốc trừ sâu sinh học",
        performedBy: "Nguyễn Văn C",
        materials: "Thuốc BT",
        quantity: "20ml/10L nước",
        cost: 30000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [
      {
        id: "harv-003",
        date: "2023-09-05",
        quantity: 52,
        quality: "A",
        price: 125000,
        totalRevenue: 6500000,
        buyer: "Công ty TNHH Trái cây Xuất khẩu",
      },
    ],
  },
  {
    id: "crop-003",
    code: "CP-ROB-003",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=1000",
    plantedDate: "2020-08-15",
    seedType: "Cây ghép TR4",
    variety: "Robusta",
    groupCropName: "Cây công nghiệp (Industrial Crops)",
    notes: "Cây cho năng suất ổn định",
    status: "healthy",
    regionId: 3,
    regionName: "Đồi Cà phê Buôn Ma Thuột",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 8,
    coordinate: { lat: 12.67, lng: 108.04 },

    growthStage: "Sinh trưởng thân lá",
    expectedHarvestDate: "2024-12-15",
    actualAge: 34,

    certifications: [],

    cultivationHistory: [
      {
        id: "cult-005",
        date: "2024-01-18",
        activity: "Điều trị bệnh",
        description: "Xử lý bệnh thán thư",
        performedBy: "Chuyên gia bảo vệ thực vật",
        materials: "Thuốc Score 250EC",
        quantity: "10ml/10L nước",
        cost: 80000,
      },
    ],

    diseaseHistory: [
      {
        id: "dis-002",
        date: "2024-01-10",
        diseaseName: "Thán thư",
        severity: "high",
        affectedArea: "Lá, cành non",
        symptoms: "Lá có đốm nâu, cành khô",
        treatment: "Phun thuốc Score 250EC, cắt bỏ cành bệnh",
        treatmentDate: "2024-01-18",
        recoveryStatus: "treating",
        notes: "Đang theo dõi",
      },
    ],

    harvestHistory: [],
  },
  {
    id: "crop-004",
    code: "MC-OC-004",
    name: "Mắc ca OC",
    image:
      "https://images.unsplash.com/photo-1596502012015-849ede6802c6?auto=format&fit=crop&q=80&w=1000",
    plantedDate: "2019-03-10",
    seedType: "Cây ghép",
    variety: "OC",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng mạnh, đã bắt đầu cho quả bói",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.522615, lng: 108.042614 },

    growthStage: "Đậu quả",
    expectedHarvestDate: "2024-03-20",
    actualAge: 41,

    certifications: [
      {
        id: "cert-004",
        name: "Rainforest Alliance",
        issuer: "Rainforest Alliance",
        issueDate: "2023-04-01",
        expiryDate: "2026-04-01",
        certificateNumber: "RA-VN-2023-156",
        status: "valid",
      },
      {
        id: "cert-005",
        name: "UTZ Certified",
        issuer: "UTZ Vietnam",
        issueDate: "2023-05-10",
        expiryDate: "2025-05-10",
        certificateNumber: "UTZ-2023-789",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-006",
        date: "2024-01-12",
        activity: "Bón phân",
        description: "Bón phân NPK chuyên dụng cho cà phê",
        performedBy: "Lê Văn D",
        materials: "Phân NPK 20-10-10",
        quantity: "300g/cây",
        cost: 35000,
      },
      {
        id: "cult-007",
        date: "2024-01-05",
        activity: "Làm cỏ",
        description: "Làm sạch cỏ dại xung quanh gốc",
        performedBy: "Đội làm vườn",
        cost: 20000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [
      {
        id: "harv-004",
        date: "2023-11-15",
        quantity: 28,
        quality: "A",
        price: 45000,
        totalRevenue: 1260000,
        buyer: "Công ty Cà phê Trung Nguyên",
      },
      {
        id: "harv-005",
        date: "2023-03-20",
        quantity: 25,
        quality: "B",
        price: 38000,
        totalRevenue: 950000,
        buyer: "Hợp tác xã Cà phê",
      },
    ],
  },
  {
    id: "crop-005",
    code: "KM-KM94-005",
    name: "Khoai mì KM94",
    image: "https://media.vneconomy.vn/images/2021/06/15/khoai-mi.jpg",
    plantedDate: "2023-05-15",
    seedType: "Hom giống",
    variety: "KM94",
    groupCropName: "Cây lương thực (Cereal & Grain)",
    notes: "Phát triển củ tốt",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Bình Phước Alpha",
    areaId: 1,
    areaName: "Khu vực khoai mì",
    plotId: "plot-1-2",
    plotName: "Lô M1 - KM94",
    rowNumber: 8,
    coordinate: { lat: 11.549, lng: 106.901 },
    growthStage: "Phát triển củ",
    expectedHarvestDate: "2024-04-20",
    actualAge: 10,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-006",
    code: "DN-DT84-006",
    name: "Đậu nành DT84",
    image: "https://media.vneconomy.vn/images/2021/08/17/dau-nanh.jpg",
    plantedDate: "2024-01-10",
    seedType: "Hạt giống",
    variety: "DT84",
    groupCropName: "Cây lương thực (Cereal & Grain)",
    notes: "Đang giai đoạn ra hoa",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Bình Phước Alpha",
    areaId: 1,
    areaName: "Khu vực đậu nành",
    plotId: "plot-1-1",
    plotName: "Lô D1 - DT84",
    rowNumber: 1,
    coordinate: { lat: 11.546, lng: 106.894 },
    growthStage: "Ra hoa",
    expectedHarvestDate: "2024-05-10",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-007",
    code: "NGO-NK-007",
    name: "Ngô NK7328",
    image: "https://media.baochinhphu.vn/images/2023/12/30/ngo.jpg",
    plantedDate: "2023-12-05",
    seedType: "Hạt giống lai",
    variety: "NK7328",
    groupCropName: "Cây lương thực (Cereal & Grain)",
    notes: "Đang trổ cờ",
    status: "healthy",
    regionId: 2,
    regionName: "Nông trại Hữu cơ Đồng Nai",
    areaId: 3,
    areaName: "Cánh đồng ngô",
    plotId: "plot-2-1",
    plotName: "Lô N1 - Bắp",
    rowNumber: 4,
    coordinate: { lat: 10.962, lng: 107.228 },
    growthStage: "Trổ cờ",
    expectedHarvestDate: "2024-04-20",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-008",
    code: "CS-RR-008",
    name: "Cao su RRIV 106",
    image:
      "https://vov.vn/sites/default/files/styles/facebook/public/2021-03/cao_su.jpg",
    plantedDate: "2018-01-20",
    seedType: "Cây ghép",
    variety: "RRIV 106",
    groupCropName: "Cây công nghiệp (Industrial Crops)",
    notes: "Đang trong thời kỳ khai thác mủ",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Bình Phước Alpha",
    areaId: 1,
    areaName: "Vườn cao su",
    plotId: "plot-1-3",
    plotName: "Lô CS1",
    rowNumber: 6,
    coordinate: { lat: 11.543, lng: 106.913 },
    growthStage: "Khai thác mủ",
    expectedHarvestDate: "2024-12-31",
    actualAge: 74,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-009",
    code: "CHE-KT-009",
    name: "Chè Kim Tuyên",
    image: "https://media.vneconomy.vn/images/2021/10/26/che.jpg",
    plantedDate: "2021-06-10",
    seedType: "Cây giâm cành",
    variety: "Kim Tuyên",
    groupCropName: "Cây công nghiệp (Industrial Crops)",
    notes: "Hái búp định kỳ",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.518056, lng: 108.043354 },
    growthStage: "Thu hoạch búp",
    expectedHarvestDate: "2024-03-25",
    actualAge: 33,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-010",
    code: "TIEU-VL-010",
    name: "Hồ tiêu Vĩnh Linh",
    image: "https://vneconomy.vn/cache/original/2021/04/15/tieu.jpg",
    plantedDate: "2020-09-15",
    seedType: "Dây thân",
    variety: "Vĩnh Linh",
    groupCropName: "Cây công nghiệp (Industrial Crops)",
    notes: "Cây phát triển tốt, chuỗi tiêu dài",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Bình Phước Alpha",
    areaId: 1,
    areaName: "Vườn tiêu",
    plotId: "plot-1-3",
    plotName: "Lô T1",
    rowNumber: 19,
    coordinate: { lat: 11.521993, lng: 108.046386 },
    growthStage: "Phát triển quả",
    expectedHarvestDate: "2024-05-15",
    actualAge: 42,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-011",
    code: "TREE-011",
    name: "Cà phê Arabica",
    image:
      "https://bizweb.dktcdn.net/100/270/753/articles/ca-phe-arabica-la-gi-ca-phe-robusta-la-gi-phan-biet-arabica-tipsnote-800x550-2.jpg?v=1718792655900",
    plantedDate: "2021-02-20",
    seedType: "Hạt giống Catimor",
    variety: "Arabica Cầu Đất",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây phát triển chậm do thời tiết",
    status: "healthy",

    regionId: 3,
    regionName: "Đồi Cà phê Buôn Ma Thuột",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 12.68, lng: 108.03 },

    growthStage: "Ra hoa",
    expectedHarvestDate: "2024-11-25",
    actualAge: 35,

    certifications: [
      {
        id: "cert-013",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-11-01",
        expiryDate: "2025-11-01",
        certificateNumber: "ORG-VN-2023-234",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-017",
        date: "2024-01-15",
        activity: "Bón phân",
        description: "Bón phân hữu cơ",
        performedBy: "Lê Văn D",
        materials: "Phân hữu cơ vi sinh",
        quantity: "2kg/cây",
        cost: 28000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [],
  },
  {
    id: "crop-012",
    code: "TREE-012",
    name: "Sầu riêng Kho Qua Xanh",
    image:
      "https://bizweb.dktcdn.net/100/428/240/articles/7-6-sau-rieng-kho-qua-xanh.png?v=1649077760710",
    plantedDate: "2022-07-10",
    seedType: "Hạt giống F1",
    variety: "Kho Qua Xanh",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây non, đang phát triển",
    status: "healthy",

    regionId: 1,
    regionName: "Vùng Bình Phước Alpha",
    areaId: 1,
    areaName: "Khu vực A - Sầu riêng",
    plotId: "plot-1-2",
    plotName: "Lô A2 - Dona",
    rowNumber: 10,
    coordinate: { lat: 11.547, lng: 106.902 },

    growthStage: "Sinh trưởng thân lá",
    expectedHarvestDate: "2025-06-15",
    actualAge: 18,

    certifications: [],

    cultivationHistory: [
      {
        id: "cult-018",
        date: "2024-01-18",
        activity: "Bón phân",
        description: "Bón phân NPK cho cây non",
        performedBy: "Nguyễn Văn A",
        materials: "Phân NPK 16-16-8",
        quantity: "1kg/cây",
        cost: 25000,
      },
      {
        id: "cult-019",
        date: "2024-01-08",
        activity: "Làm cỏ",
        description: "Làm sạch cỏ xung quanh gốc",
        performedBy: "Đội làm vườn",
        cost: 15000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [],
  },
  {
    id: "crop-013",
    code: "TREE-013",
    name: "Nhãn Ido",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTugEWQ-XCr324GHHIKsLOx_PBtU1faGIfWYw&s",
    plantedDate: "2019-10-05",
    seedType: "Cây giống ghép",
    variety: "Nhãn Ido Thái Lan",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây cho quả ngọt, năng suất cao",
    status: "harvesting",

    regionId: 2,
    regionName: "Nông trại Hữu cơ Đồng Nai",
    areaId: 3,
    areaName: "Vườn rau thủy canh",
    plotId: "plot-2-1",
    plotName: "Lô C1 - Thủy canh",
    rowNumber: 3,
    coordinate: { lat: 10.963, lng: 107.224 },

    growthStage: "Thu hoạch",
    expectedHarvestDate: "2024-01-30",
    actualAge: 51,

    certifications: [
      {
        id: "cert-014",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Đồng Nai",
        issueDate: "2023-06-15",
        expiryDate: "2025-06-15",
        certificateNumber: "VG-DN-2023-089",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-020",
        date: "2024-01-10",
        activity: "Phun thuốc",
        description: "Phun thuốc phòng sâu đục quả",
        performedBy: "Trần Văn H",
        materials: "Thuốc Decis 2.5EC",
        quantity: "10ml/10L",
        cost: 35000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [
      {
        id: "harv-013",
        date: "2023-07-20",
        quantity: 85,
        quality: "A",
        price: 55000,
        totalRevenue: 4675000,
        buyer: "Chợ đầu mối Thủ Đức",
      },
    ],
  },
  {
    id: "crop-014",
    code: "TREE-014",
    name: "Chôm chôm Nhãn",
    image: "https://thuyanhfruits.com/wp-content/uploads/2021/02/unnamed.png",
    plantedDate: "2020-04-12",
    seedType: "Cây giống ghép",
    variety: "Chôm chôm Nhãn",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây phát triển bình thường",
    status: "healthy",

    regionId: 2,
    regionName: "Nông trại Hữu cơ Đồng Nai",
    areaId: 3,
    areaName: "Vườn rau thủy canh",
    plotId: "plot-2-1",
    plotName: "Lô C1 - Thủy canh",
    rowNumber: 7,
    coordinate: { lat: 10.965, lng: 107.232 },

    growthStage: "Đậu quả",
    expectedHarvestDate: "2024-05-25",
    actualAge: 45,

    certifications: [],

    cultivationHistory: [
      {
        id: "cult-021",
        date: "2024-01-14",
        activity: "Tưới nước",
        description: "Tưới phun mưa",
        performedBy: "Hệ thống tự động",
        quantity: "70L/cây",
      },
    ],

    diseaseHistory: [
      {
        id: "dis-003",
        date: "2023-12-05",
        diseaseName: "Bệnh đốm lá",
        severity: "low",
        affectedArea: "Lá già",
        symptoms: "Lá có đốm vàng nhỏ",
        treatment: "Phun thuốc đồng",
        treatmentDate: "2023-12-08",
        recoveryStatus: "recovered",
        notes: "Đã khỏi hoàn toàn",
      },
    ],

    harvestHistory: [
      {
        id: "harv-014",
        date: "2023-11-10",
        quantity: 48,
        quality: "B",
        price: 32000,
        totalRevenue: 1536000,
        buyer: "Chợ địa phương",
      },
    ],
  },
  {
    id: "crop-015",
    code: "TREE-015",
    name: "Măng cụt",
    image:
      "https://media.vov.vn/sites/default/files/styles/large/public/2025-08/mang-cut.jpg",
    plantedDate: "2018-11-20",
    seedType: "Cây giống",
    variety: "Măng cụt Miền Tây",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây lớn, sắp cho quả",
    status: "healthy",

    regionId: 2,
    regionName: "Nông trại Hữu cơ Đồng Nai",
    areaId: 3,
    areaName: "Vườn rau thủy canh",
    plotId: "plot-2-1",
    plotName: "Lô C1 - Thủy canh",
    rowNumber: 2,
    coordinate: { lat: 10.968, lng: 107.226 },

    growthStage: "Ra hoa",
    expectedHarvestDate: "2024-09-10",
    actualAge: 62,

    certifications: [
      {
        id: "cert-015",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-12-01",
        expiryDate: "2025-12-01",
        certificateNumber: "ORG-VN-2023-456",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-022",
        date: "2024-01-11",
        activity: "Bón phân",
        description: "Bón phân hữu cơ",
        performedBy: "Hoàng Văn F",
        materials: "Phân chuồng ủ hoai",
        quantity: "15kg/cây",
        cost: 60000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [],
  },
  {
    id: "crop-10-000",
    code: "TREE-10-000",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-06-06",
    seedType: "Cây thực sinh",
    variety: "Ri6 Chợ Lách",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.525, lng: 108.045 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 42,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-001",
    code: "TREE-10-001",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-03-11",
    seedType: "Cây thực sinh",
    variety: "Booth 7 Việt",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 8,
    coordinate: { lat: 11.524047, lng: 108.046187 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 16,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-002",
    code: "TREE-10-002",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-06-24",
    seedType: "Cây ghép",
    variety: "H2",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 1,
    coordinate: { lat: 11.522615, lng: 108.042614 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 59,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-003",
    code: "TREE-10-003",
    name: "Sầu riêng Dona",
    image:
      "https://traicaytonyteo.com/uploads/source/sau-rieng-dona-thai-2.jpg",
    plantedDate: "2023-08-22",
    seedType: "Cây ghép",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.52798, lng: 108.044923 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 54,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-004",
    code: "TREE-10-004",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-10-07",
    seedType: "Cây ghép",
    variety: "H2",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.519495, lng: 108.045502 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 50,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-005",
    code: "TREE-10-005",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-02-05",
    seedType: "Cây thực sinh",
    variety: "OC",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.520247, lng: 108.048164 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 28,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-006",
    code: "TREE-10-006",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-01-13",
    seedType: "Hạt giống F1",
    variety: "Catimor",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.526802, lng: 108.047753 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 24,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-007",
    code: "TREE-10-007",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-08-21",
    seedType: "Hạt giống F1",
    variety: "Ri6 Vĩnh Long",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 11,
    coordinate: { lat: 11.518379, lng: 108.049973 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 24,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-008",
    code: "TREE-10-008",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-03-01",
    seedType: "Cây ghép",
    variety: "TR9",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 7,
    coordinate: { lat: 11.526556, lng: 108.047038 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 30,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-009",
    code: "TREE-10-009",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-05-18",
    seedType: "Hạt giống F1",
    variety: "246",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.518056, lng: 108.043354 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 44,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-010",
    code: "TREE-10-010",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-09-01",
    seedType: "Hạt giống F1",
    variety: "Booth 7 Mỹ",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 19,
    coordinate: { lat: 11.521993, lng: 108.046386 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 42,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-011",
    code: "TREE-10-011",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-08-04",
    seedType: "Cây ghép",
    variety: "Ri6 Vĩnh Long",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.524258, lng: 108.043783 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 18,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-012",
    code: "TREE-10-012",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-05-16",
    seedType: "Cây ghép",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 11,
    coordinate: { lat: 11.519304, lng: 108.047283 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 36,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-013",
    code: "TREE-10-013",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-09-04",
    seedType: "Cây ghép",
    variety: "Typica",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.527991, lng: 108.042941 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 46,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-014",
    code: "TREE-10-014",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-09-07",
    seedType: "Hạt giống F1",
    variety: "Booth 7 Mỹ",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 8,
    coordinate: { lat: 11.52234, lng: 108.04412 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 45,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-015",
    code: "TREE-10-015",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-06-27",
    seedType: "Cây thực sinh",
    variety: "Typica",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.526375, lng: 108.045185 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 20,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-016",
    code: "TREE-10-016",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-01-17",
    seedType: "Hạt giống F1",
    variety: "TR4",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.523737, lng: 108.040425 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 21,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-017",
    code: "TREE-10-017",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-04-24",
    seedType: "Hạt giống F1",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.526224, lng: 108.046067 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 26,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-018",
    code: "TREE-10-018",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-08-23",
    seedType: "Hạt giống F1",
    variety: "Booth 7 Việt",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.524302, lng: 108.046642 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 46,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-019",
    code: "TREE-10-019",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-03-22",
    seedType: "Cây ghép",
    variety: "OC",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.521467, lng: 108.041087 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 12,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-020",
    code: "TREE-10-020",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-09-03",
    seedType: "Cây thực sinh",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 10,
    coordinate: { lat: 11.521981, lng: 108.046461 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 20,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-021",
    code: "TREE-10-021",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-01-03",
    seedType: "Hạt giống F1",
    variety: "OC",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 11,
    coordinate: { lat: 11.52663, lng: 108.044512 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 17,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-022",
    code: "TREE-10-022",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-08-12",
    seedType: "Hạt giống F1",
    variety: "Ri6 Vĩnh Long",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.527499, lng: 108.04063 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 57,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-023",
    code: "TREE-10-023",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-04-24",
    seedType: "Hạt giống F1",
    variety: "Booth 7 Việt",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 4,
    coordinate: { lat: 11.522808, lng: 108.049103 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 45,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-024",
    code: "TREE-10-024",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-01-23",
    seedType: "Cây thực sinh",
    variety: "TR9",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.51942, lng: 108.045174 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 47,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-025",
    code: "TREE-10-025",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-11-17",
    seedType: "Hạt giống F1",
    variety: "H2",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.521285, lng: 108.047643 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 53,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-026",
    code: "TREE-10-026",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-09-25",
    seedType: "Cây thực sinh",
    variety: "Bourbon",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.523653, lng: 108.041587 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 59,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-027",
    code: "TREE-10-027",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-01-04",
    seedType: "Hạt giống F1",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.526468, lng: 108.04889 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 36,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-028",
    code: "TREE-10-028",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-01-23",
    seedType: "Cây thực sinh",
    variety: "Catimor",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.527147, lng: 108.048923 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 14,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-029",
    code: "TREE-10-029",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-07-24",
    seedType: "Cây ghép",
    variety: "TR9",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Cao Nguyên Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.522443, lng: 108.047801 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 59,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-000",
    code: "TREE-11-000",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-06-06",
    seedType: "Hạt giống F1",
    variety: "Ri6 Chợ Lách",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.847289, lng: 108.539816 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 27,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-001",
    code: "TREE-11-001",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-02-22",
    seedType: "Cây ghép",
    variety: "Ri6 Chợ Lách",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 7,
    coordinate: { lat: 11.84914, lng: 108.547693 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 47,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-002",
    code: "TREE-11-002",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-04-11",
    seedType: "Cây ghép",
    variety: "TR9",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.845667, lng: 108.543616 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 30,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-003",
    code: "TREE-11-003",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-12-20",
    seedType: "Cây ghép",
    variety: "Booth 7 Việt",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.843883, lng: 108.548493 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 17,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-004",
    code: "TREE-11-004",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-12-22",
    seedType: "Cây ghép",
    variety: "Typica",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.849765, lng: 108.547102 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 28,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-005",
    code: "TREE-11-005",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-03-22",
    seedType: "Cây thực sinh",
    variety: "Bourbon",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.847596, lng: 108.54532 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 46,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-006",
    code: "TREE-11-006",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-08-03",
    seedType: "Cây ghép",
    variety: "Typica",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.850274, lng: 108.54081 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 22,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-007",
    code: "TREE-11-007",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-06-20",
    seedType: "Cây thực sinh",
    variety: "Ri6 Vĩnh Long",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 10,
    coordinate: { lat: 11.848355, lng: 108.54195 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 60,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-008",
    code: "TREE-11-008",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2022-08-07",
    seedType: "Cây ghép",
    variety: "Ri6 Chợ Lách",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.850321, lng: 108.548923 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 22,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-009",
    code: "TREE-11-009",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-03-12",
    seedType: "Hạt giống F1",
    variety: "Dona Malaysia",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 4,
    coordinate: { lat: 11.844009, lng: 108.544908 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 41,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-010",
    code: "TREE-11-010",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-07-23",
    seedType: "Hạt giống F1",
    variety: "TR9",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.848325, lng: 108.548521 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 54,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-011",
    code: "TREE-11-011",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-03-18",
    seedType: "Cây ghép",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 19,
    coordinate: { lat: 11.843764, lng: 108.546178 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 52,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-012",
    code: "TREE-11-012",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-07-21",
    seedType: "Cây ghép",
    variety: "246",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 3,
    coordinate: { lat: 11.845498, lng: 108.54335 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 22,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-013",
    code: "TREE-11-013",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-03-07",
    seedType: "Cây thực sinh",
    variety: "Dona Thái",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.845658, lng: 108.546332 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 46,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-014",
    code: "TREE-11-014",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-11-12",
    seedType: "Cây ghép",
    variety: "TR9",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.851698, lng: 108.544163 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 54,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-015",
    code: "TREE-11-015",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-11-22",
    seedType: "Cây thực sinh",
    variety: "246",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.852982, lng: 108.539104 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 41,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-016",
    code: "TREE-11-016",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-02-18",
    seedType: "Cây ghép",
    variety: "Bourbon",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.85162, lng: 108.548966 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 21,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-017",
    code: "TREE-11-017",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-03-26",
    seedType: "Cây thực sinh",
    variety: "Ri6 Chợ Lách",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 4,
    coordinate: { lat: 11.850795, lng: 108.543557 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 23,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-018",
    code: "TREE-11-018",
    name: "Mắc ca",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-06-23",
    seedType: "Cây ghép",
    variety: "246",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.843081, lng: 108.548096 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 32,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-019",
    code: "TREE-11-019",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-07-19",
    seedType: "Hạt giống F1",
    variety: "Booth 7 Việt",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 18,
    coordinate: { lat: 11.84999, lng: 108.543555 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 18,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-020",
    code: "TREE-11-020",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-08-04",
    seedType: "Cây thực sinh",
    variety: "Typica",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.850315, lng: 108.546869 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 50,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-021",
    code: "TREE-11-021",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-06-01",
    seedType: "Cây ghép",
    variety: "Dona Malaysia",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 3,
    coordinate: { lat: 11.851277, lng: 108.546229 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 28,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-022",
    code: "TREE-11-022",
    name: "Sầu riêng Dona",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2019-08-08",
    seedType: "Cây thực sinh",
    variety: "Dona Malaysia",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.851905, lng: 108.541828 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 43,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-023",
    code: "TREE-11-023",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-07-02",
    seedType: "Cây ghép",
    variety: "TRS1",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 18,
    coordinate: { lat: 11.848831, lng: 108.544432 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 29,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-024",
    code: "TREE-11-024",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-03-23",
    seedType: "Cây ghép",
    variety: "TRS1",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 9,
    coordinate: { lat: 11.844843, lng: 108.547302 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 21,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-025",
    code: "TREE-11-025",
    name: "Bơ Booth 7",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2020-06-25",
    seedType: "Hạt giống F1",
    variety: "Booth 7 Mỹ",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.8482, lng: 108.54221 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 23,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-026",
    code: "TREE-11-026",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-03-26",
    seedType: "Cây thực sinh",
    variety: "Ri6 Chợ Lách",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.85091, lng: 108.547336 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 13,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-027",
    code: "TREE-11-027",
    name: "Cà phê Robusta",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2023-04-13",
    seedType: "Cây ghép",
    variety: "TRS1",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.84678, lng: 108.541686 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 42,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-028",
    code: "TREE-11-028",
    name: "Cà phê Arabica",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2018-01-14",
    seedType: "Cây thực sinh",
    variety: "Bourbon",
    groupCropName: "Cây công nghiệp (Industrial/Cash Crops)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.84559, lng: 108.543455 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 57,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-029",
    code: "TREE-11-029",
    name: "Sầu riêng Ri6",
    image:
      "https://images.unsplash.com/photo-1592150621344-c79230550bd5?q=80&w=400&auto=format&fit=crop",
    plantedDate: "2021-03-25",
    seedType: "Cây ghép",
    variety: "Ri6 Vĩnh Long",
    groupCropName: "Cây ăn trái (Fruit Trees)",
    notes: "Cây sinh trưởng tốt trên vùng cao nguyên",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Chè & Cà Phê Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 20,
    coordinate: { lat: 11.845355, lng: 108.541108 },
    growthStage: "Phát triển",
    expectedHarvestDate: "2024-11-20",
    actualAge: 41,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
];

export const GROWTH_STAGES = [
  { id: "seedling", name: "Giai đoạn cây con" },
  { id: "vegetative", name: "Sinh trưởng thân lá" },
  { id: "flowering", name: "Ra hoa" },
  { id: "fruiting", name: "Đậu quả" },
  { id: "ripening", name: "Quả chín" },
  { id: "harvesting", name: "Thu hoạch" },
];

export const ACTIVITY_TYPES = [
  { id: "watering", name: "Tưới nước" },
  { id: "fertilizing", name: "Bón phân" },
  { id: "pruning", name: "Cắt tỉa" },
  { id: "spraying", name: "Phun thuốc" },
  { id: "weeding", name: "Làm cỏ" },
  { id: "treatment", name: "Điều trị bệnh" },
  { id: "harvesting", name: "Thu hoạch" },
  { id: "other", name: "Khác" },
];

// Cultivation Zone (Vùng trồng) interfaces
export interface StaffMember {
  id: string;
  name: string;
  role: string; // Vai trò: Quản lý, Kỹ thuật viên, Công nhân
  phone: string;
  email?: string;
  assignedDate: string;
  specialization?: string; // Chuyên môn
}

export interface CropVariety {
  id: string;
  name: string; // Tên cây trồng
  variety: string; // Giống
  plantedDate: string;
  totalPlants: number; // Tổng số cây
  area: number; // Diện tích (ha)
  expectedYield: number; // Năng suất dự kiến (tấn/ha)
  status: "growing" | "flowering" | "harvesting" | "completed";
  seedType?: string; // Loại hạt giống
}

export interface CultivationPlan {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  status: "planned" | "in-progress" | "completed" | "cancelled";
  activities: {
    id: string;
    name: string;
    scheduledDate: string;
    completedDate?: string;
    assignedTo: string;
    status: "pending" | "in-progress" | "completed";
    notes?: string;
  }[];
  budget: number;
  actualCost?: number;
}

export interface CultivationZone {
  id: string;
  code: string;
  name: string;
  enterpriseId?: number; // ID doanh nghiệp
  location: string; // Địa chỉ
  province: string;
  district: string;
  ward?: string;
  totalArea: number; // Tổng diện tích (ha)
  cultivatedArea: number; // Diện tích canh tác (ha)
  coordinates: Coordinate[]; // Tọa độ bản đồ
  mapCenter: Coordinate;

  // Thông tin canh tác
  cropVarieties: CropVariety[];
  mainCrop: string; // Cây trồng chính
  soilType: string; // Loại đất
  irrigationSystem: string; // Hệ thống tưới

  // Nhân viên
  staff: StaffMember[];
  manager: string; // Người quản lý

  // Giấy chứng nhận
  certifications: Certification[];

  // Kế hoạch canh tác
  cultivationPlans: CultivationPlan[];

  // Thông tin khác
  establishedDate: string;
  status: "active" | "inactive" | "under-construction";
  notes: string;
}

export const MOCK_CULTIVATION_ZONES: CultivationZone[] = [
  {
    id: "zone-001",
    code: "ZONE-BP-001",
    name: "Vùng Sầu riêng Bình Phước",
    enterpriseId: 1,
    location: "Khu phố 3, Phường Tân Đồng, TP Đồng Xoài",
    province: "Bình Phước",
    district: "Bù Đăng",
    ward: "Xã Đức Liễu",
    totalArea: 50.5,
    cultivatedArea: 48.2,
    coordinates: [
      { lat: 11.53, lng: 106.88 },
      { lat: 11.53, lng: 106.91 },
      { lat: 11.55, lng: 106.91 },
      { lat: 11.55, lng: 106.88 },
    ],
    mapCenter: { lat: 11.54, lng: 106.895 },

    cropVarieties: [
      {
        id: "cv-001",
        name: "Sầu riêng",
        variety: "Dona Malaysia",
        plantedDate: "2020-05-15",
        totalPlants: 850,
        area: 25.5,
        expectedYield: 12,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
      {
        id: "cv-002",
        name: "Sầu riêng",
        variety: "Ri6 Thái Lan",
        plantedDate: "2019-11-20",
        totalPlants: 720,
        area: 18.2,
        expectedYield: 15,
        status: "harvesting",
        seedType: "Hạt giống F1",
      },
      {
        id: "cv-003",
        name: "Sầu riêng",
        variety: "Monthong",
        plantedDate: "2018-03-25",
        totalPlants: 180,
        area: 4.5,
        expectedYield: 18,
        status: "harvesting",
        seedType: "Hạt giống F1",
      },
    ],
    mainCrop: "Sầu riêng",
    soilType: "Đất đỏ Bazan",
    irrigationSystem: "Tưới nhỏ giọt tự động",

    staff: [
      {
        id: "staff-001",
        name: "Nguyễn Văn A",
        role: "Quản lý vùng",
        phone: "0901234567",
        email: "nguyenvana@example.com",
        assignedDate: "2020-01-15",
        specialization: "Kỹ thuật trồng sầu riêng",
      },
      {
        id: "staff-002",
        name: "Trần Văn B",
        role: "Kỹ thuật viên",
        phone: "0912345678",
        email: "tranvanb@example.com",
        assignedDate: "2020-03-01",
        specialization: "Bảo vệ thực vật",
      },
      {
        id: "staff-003",
        name: "Lê Thị C",
        role: "Kỹ thuật viên",
        phone: "0923456789",
        assignedDate: "2020-06-10",
        specialization: "Dinh dưỡng cây trồng",
      },
      {
        id: "staff-004",
        name: "Phạm Văn D",
        role: "Trưởng nhóm công nhân",
        phone: "0934567890",
        assignedDate: "2020-02-01",
      },
    ],
    manager: "Nguyễn Văn A",

    certifications: [
      {
        id: "cert-zone-001",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Bình Phước",
        issueDate: "2023-01-10",
        expiryDate: "2025-01-10",
        certificateNumber: "VG-BP-2023-001",
        status: "valid",
      },
      {
        id: "cert-zone-002",
        name: "GlobalGAP",
        issuer: "SGS Vietnam",
        issueDate: "2023-06-01",
        expiryDate: "2025-06-01",
        certificateNumber: "GG-VN-2023-089",
        status: "valid",
      },
    ],

    cultivationPlans: [
      {
        id: "plan-001",
        name: "Kế hoạch canh tác Quý 1/2024",
        startDate: "2024-01-01",
        endDate: "2024-03-31",
        status: "in-progress",
        budget: 150000000,
        actualCost: 85000000,
        activities: [
          {
            id: "act-001",
            name: "Bón phân lần 1",
            scheduledDate: "2024-01-15",
            completedDate: "2024-01-15",
            assignedTo: "Lê Thị C",
            status: "completed",
            notes: "Đã hoàn thành đúng kế hoạch",
          },
          {
            id: "act-002",
            name: "Phun thuốc phòng bệnh",
            scheduledDate: "2024-02-01",
            completedDate: "2024-02-02",
            assignedTo: "Trần Văn B",
            status: "completed",
          },
          {
            id: "act-003",
            name: "Cắt tỉa cành",
            scheduledDate: "2024-02-15",
            assignedTo: "Phạm Văn D",
            status: "in-progress",
          },
          {
            id: "act-004",
            name: "Bón phân lần 2",
            scheduledDate: "2024-03-15",
            assignedTo: "Lê Thị C",
            status: "pending",
          },
        ],
      },
      {
        id: "plan-002",
        name: "Kế hoạch thu hoạch 2024",
        startDate: "2024-04-01",
        endDate: "2024-08-31",
        status: "planned",
        budget: 200000000,
        activities: [
          {
            id: "act-005",
            name: "Thu hoạch đợt 1 - Ri6",
            scheduledDate: "2024-04-15",
            assignedTo: "Phạm Văn D",
            status: "pending",
          },
          {
            id: "act-006",
            name: "Thu hoạch đợt 2 - Monthong",
            scheduledDate: "2024-05-20",
            assignedTo: "Phạm Văn D",
            status: "pending",
          },
        ],
      },
    ],

    establishedDate: "2019-10-01",
    status: "active",
    notes:
      "Vùng trồng thử nghiệm sầu riêng chất lượng cao, áp dụng công nghệ tưới tiên tiến",
  },
  {
    id: "zone-002",
    code: "ZONE-DN-001",
    name: "Nông trại Hữu cơ Đồng Nai",
    enterpriseId: 2,
    location: "Xã Gia Kiệm, Huyện Thống Nhất",
    province: "Đồng Nai",
    district: "Định Quán",
    ward: "Xã Phụ Ngọc",
    totalArea: 120.0,
    cultivatedArea: 115.5,
    coordinates: [
      { lat: 10.957, lng: 107.22 },
      { lat: 10.957, lng: 107.23 },
      { lat: 10.965, lng: 107.23 },
      { lat: 10.965, lng: 107.22 },
    ],
    mapCenter: { lat: 10.961, lng: 107.225 },

    cropVarieties: [
      {
        id: "cv-004",
        name: "Xoài",
        variety: "Cát Hòa Lộc",
        plantedDate: "2020-12-05",
        totalPlants: 1200,
        area: 40.0,
        expectedYield: 8,
        status: "growing",
        seedType: "Cây thực sinh",
      },
      {
        id: "cv-005",
        name: "Thanh long",
        variety: "Ruột đỏ",
        plantedDate: "2022-01-20",
        totalPlants: 2500,
        area: 35.5,
        expectedYield: 20,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
      {
        id: "cv-006",
        name: "Nhãn",
        variety: "Ido Thái Lan",
        plantedDate: "2019-10-05",
        totalPlants: 800,
        area: 25.0,
        expectedYield: 10,
        status: "harvesting",
        seedType: "Hạt giống F1",
      },
      {
        id: "cv-007",
        name: "Chôm chôm",
        variety: "Chôm chôm Nhãn",
        plantedDate: "2020-04-12",
        totalPlants: 450,
        area: 15.0,
        expectedYield: 7,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
    ],
    mainCrop: "Rau màu hữu cơ",
    soilType: "Đất phù sa",
    irrigationSystem: "Tưới phun mưa",

    staff: [
      {
        id: "staff-005",
        name: "Hoàng Văn E",
        role: "Quản lý vùng",
        phone: "0945678901",
        email: "hoangvane@example.com",
        assignedDate: "2019-08-01",
        specialization: "Nông nghiệp hữu cơ",
      },
      {
        id: "staff-006",
        name: "Võ Văn F",
        role: "Kỹ thuật viên",
        phone: "0956789012",
        assignedDate: "2020-01-15",
        specialization: "Trồng trọt hữu cơ",
      },
      {
        id: "staff-007",
        name: "Đặng Thị G",
        role: "Kỹ thuật viên",
        phone: "0967890123",
        assignedDate: "2020-05-20",
        specialization: "Kiểm soát chất lượng",
      },
    ],
    manager: "Hoàng Văn E",

    certifications: [
      {
        id: "cert-zone-003",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-08-01",
        expiryDate: "2025-08-01",
        certificateNumber: "ORG-VN-2023-167",
        status: "valid",
      },
      {
        id: "cert-zone-004",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Đồng Nai",
        issueDate: "2023-06-15",
        expiryDate: "2025-06-15",
        certificateNumber: "VG-DN-2023-089",
        status: "valid",
      },
    ],

    cultivationPlans: [
      {
        id: "plan-003",
        name: "Kế hoạch canh tác hữu cơ 2024",
        startDate: "2024-01-01",
        endDate: "2024-12-31",
        status: "in-progress",
        budget: 300000000,
        actualCost: 120000000,
        activities: [
          {
            id: "act-007",
            name: "Bón phân hữu cơ",
            scheduledDate: "2024-01-20",
            completedDate: "2024-01-20",
            assignedTo: "Võ Văn F",
            status: "completed",
          },
          {
            id: "act-008",
            name: "Kiểm tra chất lượng đất",
            scheduledDate: "2024-02-10",
            completedDate: "2024-02-11",
            assignedTo: "Đặng Thị G",
            status: "completed",
          },
          {
            id: "act-009",
            name: "Phun thuốc sinh học",
            scheduledDate: "2024-03-01",
            assignedTo: "Võ Văn F",
            status: "pending",
          },
        ],
      },
    ],

    establishedDate: "2019-05-15",
    status: "active",
    notes: "Nông trại chuyên canh rau màu hữu cơ theo tiêu chuẩn quốc tế",
  },
  {
    id: "zone-003",
    code: "ZONE-DL-001",
    name: "Đồi Cà phê Buôn Ma Thuột",
    enterpriseId: 4,
    location: "Km 15, Quốc lộ 14, TP Buôn Ma Thuột",
    province: "Lâm Đồng",
    district: "Bảo Lộc",
    ward: "Phường Lộc Tiến",
    totalArea: 200.5,
    cultivatedArea: 195.0,
    coordinates: [
      { lat: 12.667, lng: 108.037 },
      { lat: 12.667, lng: 108.05 },
      { lat: 12.68, lng: 108.05 },
      { lat: 12.68, lng: 108.037 },
    ],
    mapCenter: { lat: 12.6735, lng: 108.0435 },

    cropVarieties: [
      {
        id: "cv-008",
        name: "Cà phê",
        variety: "Robusta Đắk Lắk",
        plantedDate: "2020-08-15",
        totalPlants: 15000,
        area: 150.0,
        expectedYield: 2.5,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
      {
        id: "cv-009",
        name: "Cà phê",
        variety: "Arabica Cầu Đất",
        plantedDate: "2021-02-20",
        totalPlants: 5000,
        area: 45.0,
        expectedYield: 1.8,
        status: "growing",
        seedType: "Cây thực sinh",
      },
    ],
    mainCrop: "Cà phê Robusta",
    soilType: "Đất đỏ Bazan",
    irrigationSystem: "Tưới nhỏ giọt",

    staff: [
      {
        id: "staff-008",
        name: "Nguyễn Văn H",
        role: "Quản lý vùng",
        phone: "0978901234",
        email: "nguyenvanh@example.com",
        assignedDate: "2020-06-01",
        specialization: "Kỹ thuật trồng cà phê",
      },
      {
        id: "staff-009",
        name: "Lê Văn I",
        role: "Kỹ thuật viên",
        phone: "0989012345",
        assignedDate: "2020-08-01",
        specialization: "Chế biến cà phê",
      },
      {
        id: "staff-010",
        name: "Trần Thị K",
        role: "Kỹ thuật viên",
        phone: "0990123456",
        assignedDate: "2021-01-10",
        specialization: "Bảo vệ thực vật",
      },
    ],
    manager: "Nguyễn Văn H",

    certifications: [
      {
        id: "cert-zone-005",
        name: "Rainforest Alliance",
        issuer: "Rainforest Alliance",
        issueDate: "2023-04-01",
        expiryDate: "2026-04-01",
        certificateNumber: "RA-VN-2023-156",
        status: "valid",
      },
      {
        id: "cert-zone-006",
        name: "UTZ Certified",
        issuer: "UTZ Vietnam",
        issueDate: "2023-05-10",
        expiryDate: "2025-05-10",
        certificateNumber: "UTZ-2023-789",
        status: "valid",
      },
    ],

    cultivationPlans: [
      {
        id: "plan-004",
        name: "Kế hoạch thu hoạch cà phê 2024",
        startDate: "2024-10-01",
        endDate: "2024-12-31",
        status: "planned",
        budget: 500000000,
        activities: [
          {
            id: "act-010",
            name: "Chuẩn bị thu hoạch",
            scheduledDate: "2024-10-01",
            assignedTo: "Lê Văn I",
            status: "pending",
          },
          {
            id: "act-011",
            name: "Thu hoạch đợt 1",
            scheduledDate: "2024-11-01",
            assignedTo: "Nguyễn Văn H",
            status: "pending",
          },
        ],
      },
    ],

    establishedDate: "2020-05-01",
    status: "active",
    notes: "Vùng cà phê xuất khẩu chất lượng cao, áp dụng quy trình bền vững",
  },
];
