import type { Coordinate } from "../region-chart/constants";

// Crop/Plant detailed information
export interface CropDetail {
  id: string;
  code: string;
  name: string;
  image: string;
  plantedDate: string;
  seedType: string; // Loại hạt giống
  variety: string; // Giống cây
  groupCropName: string; // Nhóm cây trồng
  notes: string;
  status: "healthy" | "diseased" | "harvesting" | "removed";

  // Location information
  regionId: number;
  regionName: string;
  areaId: number;
  areaName: string;
  plotId: string;
  plotName: string;
  rowNumber?: number; // Số hàng
  coordinate: Coordinate;

  // Growth cycle
  growthStage: string; // Giai đoạn sinh trưởng
  expectedHarvestDate: string;
  actualAge: number; // Tuổi cây (tháng)

  // Certifications
  certifications: Certification[];

  // History
  cultivationHistory: CultivationRecord[];
  diseaseHistory: DiseaseRecord[];
  harvestHistory: HarvestRecord[];
}

export interface Certification {
  id: string;
  name: string;
  issuer: string; // Đơn vị cấp
  issueDate: string;
  expiryDate: string;
  certificateNumber: string;
  status: "valid" | "expired" | "pending";
  documentUrl?: string;
}

export interface CultivationRecord {
  id: string;
  date: string;
  activity: string; // Hoạt động: tưới nước, bón phân, cắt tỉa, etc.
  description: string;
  performedBy: string;
  materials?: string; // Vật tư sử dụng
  quantity?: string;
  cost?: number;
  notes?: string;
}

export interface DiseaseRecord {
  id: string;
  date: string;
  diseaseName: string;
  severity: "low" | "medium" | "high";
  affectedArea: string; // Vùng bị ảnh hưởng
  symptoms: string;
  treatment: string;
  treatmentDate: string;
  recoveryStatus: "recovered" | "treating" | "severe";
  images?: string[];
  notes?: string;
}

export interface HarvestRecord {
  id: string;
  date: string;
  quantity: number; // kg
  quality: "A" | "B" | "C";
  price: number; // VND/kg
  totalRevenue: number;
  buyer?: string;
  notes?: string;
}

// Mock data
export const MOCK_CROPS: CropDetail[] = [
  {
    id: "crop-001",
    code: "LUA-ST25-001",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2020-05-15",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Lúa An Giang Alpha",
    areaId: 1,
    areaName: "Khu ruộng lúa hữu cơ",
    plotId: "plot-1-1",
    plotName: "Lô 1-1 - Ruộng Lúa ST25",
    rowNumber: 3,
    coordinate: { lat: 11.545, lng: 106.895 },

    growthStage: "Mạ",
    expectedHarvestDate: "2020-08-28",
    actualAge: 1, // 45 tháng

    certifications: [
      {
        id: "cert-001",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp An Giang",
        issueDate: "2023-01-10",
        expiryDate: "2025-01-10",
        certificateNumber: "VG-BP-2023-001",
        status: "valid",
      },
      {
        id: "cert-002",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-03-15",
        expiryDate: "2024-03-15",
        certificateNumber: "ORG-VN-2023-045",
        status: "expired",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-001",
        date: "2024-01-15",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa ST25 theo giai đoạn sinh trưởng",
        performedBy: "Nguyễn Văn A",
        materials: "Phân hữu cơ vi sinh",
        quantity: "2kg/ruộng",
        cost: 50000,
        notes: "Thời tiết thuận lợi",
      },
      {
        id: "cult-002",
        date: "2024-01-10",
        activity: "Tưới nước",
        description:
          "Điều tiết nước mặt ruộng cho lúa ST25 theo phương pháp ngập khô xen kẽ",
        performedBy: "Hệ thống tự động",
        quantity: "50L/ruộng",
        notes: "Độ ẩm đất 65%",
      },
      {
        id: "cult-003",
        date: "2024-01-05",
        activity: "Cắt tỉa",
        description: "Làm cỏ, sục bùn và quản lý dịch hại cho lúa ST25",
        performedBy: "Trần Văn B",
        notes: "Ruộng thông thoáng, hạn chế sâu bệnh",
      },
    ],

    diseaseHistory: [
      {
        id: "dis-001",
        date: "2023-11-20",
        diseaseName: "Đạo ôn lá",
        severity: "medium",
        affectedArea: "Lá, cổ bông và thân lúa",
        symptoms:
          "Vết bệnh hình thoi trên lá, cổ bông bị nâu, cây sinh trưởng chậm",
        treatment:
          "Cạo sạch vết bệnh, quét thuốc gốc đồng và xử lý nấm nấm đạo ôn",
        treatmentDate: "2023-11-21",
        recoveryStatus: "recovered",
        notes: "Đã hồi phục sau 2 tuần",
      },
    ],

    harvestHistory: [
      {
        id: "harv-001",
        date: "2023-08-15",
        quantity: 4500,
        quality: "A",
        price: 8500,
        totalRevenue: 38250000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
        notes: "Chất lượng tốt, giá cao",
      },
      {
        id: "harv-002",
        date: "2023-02-10",
        quantity: 3800,
        quality: "A",
        price: 8500,
        totalRevenue: 32300000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
        notes: "Vụ đầu tiên",
      },
    ],
  },
  {
    id: "crop-002",
    code: "LUA-OM5451-002",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2023-11-20",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "harvesting",
    regionId: 2,
    regionName: "Nông trại Lúa hữu cơ Đồng Tháp",
    areaId: 3,
    areaName: "Cánh đồng lúa VietGAP",
    plotId: "plot-2-1",
    plotName: "Lô 2-1 - Ruộng Lúa OM5451",
    rowNumber: 1,
    coordinate: { lat: 10.963, lng: 107.224 },

    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2024-03-05",
    actualAge: 2,

    certifications: [
      {
        id: "cert-003",
        name: "GlobalGAP",
        issuer: "SGS Vietnam",
        issueDate: "2023-06-01",
        expiryDate: "2025-06-01",
        certificateNumber: "GG-VN-2023-089",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-004",
        date: "2024-01-20",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa OM5451 theo giai đoạn sinh trưởng",
        performedBy: "Nguyễn Văn C",
        materials: "Phân hữu cơ vi sinh",
        quantity: "90kg/ha",
        cost: 30000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [
      {
        id: "harv-003",
        date: "2023-09-05",
        quantity: 5200,
        quality: "A",
        price: 9000,
        totalRevenue: 46800000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
      },
    ],
  },
  {
    id: "crop-003",
    code: "LUA-JAS85-003",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2020-08-15",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 3,
    regionName: "Vùng Lúa chất lượng cao Kiên Giang",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 8,
    coordinate: { lat: 12.67, lng: 108.04 },

    growthStage: "Làm đòng",
    expectedHarvestDate: "2020-11-30",
    actualAge: 3,

    certifications: [],

    cultivationHistory: [
      {
        id: "cult-005",
        date: "2024-01-18",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa Jasmine 85 theo giai đoạn sinh trưởng",
        performedBy: "Chuyên gia bảo vệ thực vật",
        materials: "Phân hữu cơ vi sinh",
        quantity: "80kg/ha nước",
        cost: 80000,
      },
    ],

    diseaseHistory: [
      {
        id: "dis-002",
        date: "2024-01-10",
        diseaseName: "Đạo ôn lá",
        severity: "high",
        affectedArea: "Lá, cổ bông và thân lúa",
        symptoms:
          "Vết bệnh hình thoi trên lá, cổ bông bị nâu, cây sinh trưởng chậm",
        treatment:
          "Cạo sạch vết bệnh, quét thuốc gốc đồng và xử lý nấm nấm đạo ôn",
        treatmentDate: "2024-01-18",
        recoveryStatus: "treating",
        notes: "Đang theo dõi",
      },
    ],

    harvestHistory: [],
  },
  {
    id: "crop-004",
    code: "LUA-JPN-004",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2019-03-10",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.522615, lng: 108.042614 },

    growthStage: "Trổ bông",
    expectedHarvestDate: "2019-06-26",
    actualAge: 4,

    certifications: [
      {
        id: "cert-004",
        name: "Rainforest Alliance",
        issuer: "Rainforest Alliance",
        issueDate: "2023-04-01",
        expiryDate: "2026-04-01",
        certificateNumber: "RA-VN-2023-156",
        status: "valid",
      },
      {
        id: "cert-005",
        name: "UTZ Certified",
        issuer: "UTZ Vietnam",
        issueDate: "2023-05-10",
        expiryDate: "2025-05-10",
        certificateNumber: "UTZ-2023-789",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-006",
        date: "2024-01-12",
        activity: "Bón phân",
        description: "Bón phân hữu cơ và NPK cân đối cho lúa Japonica",
        performedBy: "Lê Văn D",
        materials: "Phân hữu cơ vi sinh",
        quantity: "300g/ruộng",
        cost: 35000,
      },
      {
        id: "cult-007",
        date: "2024-01-05",
        activity: "Tưới nước",
        description:
          "Điều tiết nước mặt ruộng cho lúa Japonica theo phương pháp ngập khô xen kẽ",
        performedBy: "Đội làm vườn",
        cost: 20000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [
      {
        id: "harv-004",
        date: "2023-11-15",
        quantity: 2800,
        quality: "A",
        price: 10000,
        totalRevenue: 28000000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
      },
      {
        id: "harv-005",
        date: "2023-03-20",
        quantity: 2500,
        quality: "B",
        price: 10000,
        totalRevenue: 25000000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
      },
    ],
  },
  {
    id: "crop-005",
    code: "LUA-NH9-005",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2023-05-15",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Lúa An Giang Alpha",
    areaId: 1,
    areaName: "Khu ruộng lúa hữu cơ",
    plotId: "plot-1-2",
    plotName: "Lô 1-2 - Ruộng Lúa Nàng Hoa 9",
    rowNumber: 8,
    coordinate: { lat: 11.549, lng: 106.901 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2023-09-01",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-006",
    code: "LUA-OM18-006",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2024-01-10",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Lúa An Giang Alpha",
    areaId: 1,
    areaName: "Khu ruộng lúa hữu cơ",
    plotId: "plot-1-1",
    plotName: "Lô 1-1 - Ruộng Lúa OM18",
    rowNumber: 1,
    coordinate: { lat: 11.546, lng: 106.894 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2024-04-29",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-007",
    code: "LUA-ST25-007",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2023-12-05",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 2,
    regionName: "Nông trại Lúa hữu cơ Đồng Tháp",
    areaId: 3,
    areaName: "Cánh đồng lúa VietGAP",
    plotId: "plot-2-1",
    plotName: "Lô 2-1 - Ruộng Lúa ST25",
    rowNumber: 4,
    coordinate: { lat: 10.962, lng: 107.228 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2024-03-25",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-008",
    code: "LUA-OM5451-008",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2018-01-20",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Lúa An Giang Alpha",
    areaId: 1,
    areaName: "Khu ruộng lúa hữu cơ",
    plotId: "plot-1-3",
    plotName: "Lô 1-3 - Ruộng Lúa OM5451",
    rowNumber: 6,
    coordinate: { lat: 11.543, lng: 106.913 },
    growthStage: "Mạ",
    expectedHarvestDate: "2018-05-12",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-009",
    code: "LUA-JAS85-009",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2021-06-10",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.518056, lng: 108.043354 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2021-10-01",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-010",
    code: "LUA-JPN-010",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2020-09-15",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 1,
    regionName: "Vùng Lúa An Giang Alpha",
    areaId: 1,
    areaName: "Khu ruộng lúa hữu cơ",
    plotId: "plot-1-3",
    plotName: "Lô 1-3 - Ruộng Lúa Japonica",
    rowNumber: 19,
    coordinate: { lat: 11.521993, lng: 108.046386 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2021-01-07",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-011",
    code: "LUA-NH9-011",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2021-02-20",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",

    regionId: 3,
    regionName: "Vùng Lúa chất lượng cao Kiên Giang",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 12.68, lng: 108.03 },

    growthStage: "Trổ bông",
    expectedHarvestDate: "2021-06-15",
    actualAge: 3,

    certifications: [
      {
        id: "cert-013",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-11-01",
        expiryDate: "2025-11-01",
        certificateNumber: "ORG-VN-2023-234",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-017",
        date: "2024-01-15",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa TBR225 theo giai đoạn sinh trưởng",
        performedBy: "Lê Văn D",
        materials: "Phân hữu cơ vi sinh",
        quantity: "2kg/ruộng",
        cost: 28000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [],
  },
  {
    id: "crop-012",
    code: "LUA-OM18-012",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2022-07-10",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",

    regionId: 1,
    regionName: "Vùng Lúa An Giang Alpha",
    areaId: 1,
    areaName: "Khu ruộng lúa hữu cơ",
    plotId: "plot-1-2",
    plotName: "Lô 1-2 - Ruộng Lúa OM18",
    rowNumber: 10,
    coordinate: { lat: 11.547, lng: 106.902 },

    growthStage: "Chín sữa",
    expectedHarvestDate: "2022-11-03",
    actualAge: 4,

    certifications: [],

    cultivationHistory: [
      {
        id: "cult-018",
        date: "2024-01-18",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa Bắc Thơm 7 theo giai đoạn sinh trưởng",
        performedBy: "Nguyễn Văn A",
        materials: "Phân hữu cơ vi sinh",
        quantity: "1kg/ruộng",
        cost: 25000,
      },
      {
        id: "cult-019",
        date: "2024-01-08",
        activity: "Tưới nước",
        description:
          "Điều tiết nước mặt ruộng cho lúa Bắc Thơm 7 theo phương pháp ngập khô xen kẽ",
        performedBy: "Đội làm vườn",
        cost: 15000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [],
  },
  {
    id: "crop-013",
    code: "LUA-ST25-013",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2019-10-05",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "harvesting",

    regionId: 2,
    regionName: "Nông trại Lúa hữu cơ Đồng Tháp",
    areaId: 3,
    areaName: "Cánh đồng lúa VietGAP",
    plotId: "plot-2-1",
    plotName: "Lô 2-1 - Ruộng Lúa ST25",
    rowNumber: 3,
    coordinate: { lat: 10.963, lng: 107.224 },

    growthStage: "Chín vàng",
    expectedHarvestDate: "2020-01-30",
    actualAge: 1,

    certifications: [
      {
        id: "cert-014",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Đồng Tháp",
        issueDate: "2023-06-15",
        expiryDate: "2025-06-15",
        certificateNumber: "VG-DN-2023-089",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-020",
        date: "2024-01-10",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa OM4900 theo giai đoạn sinh trưởng",
        performedBy: "Trần Văn H",
        materials: "Phân hữu cơ vi sinh",
        quantity: "80kg/ha",
        cost: 35000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [
      {
        id: "harv-013",
        date: "2023-07-20",
        quantity: 8500,
        quality: "A",
        price: 9500,
        totalRevenue: 80750000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
      },
    ],
  },
  {
    id: "crop-014",
    code: "LUA-OM5451-014",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2020-04-12",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",

    regionId: 2,
    regionName: "Nông trại Lúa hữu cơ Đồng Tháp",
    areaId: 3,
    areaName: "Cánh đồng lúa VietGAP",
    plotId: "plot-2-1",
    plotName: "Lô 2-1 - Ruộng Lúa OM5451",
    rowNumber: 7,
    coordinate: { lat: 10.965, lng: 107.232 },

    growthStage: "Thu hoạch",
    expectedHarvestDate: "2020-08-08",
    actualAge: 2,

    certifications: [],

    cultivationHistory: [
      {
        id: "cult-021",
        date: "2024-01-14",
        activity: "Bón phân",
        description:
          "Bón phân hữu cơ, NPK và kali cân đối cho lúa ML202 theo giai đoạn sinh trưởng",
        performedBy: "Hệ thống tự động",
        quantity: "70L/ruộng",
      },
    ],

    diseaseHistory: [
      {
        id: "dis-003",
        date: "2023-12-05",
        diseaseName: "Đạo ôn lá",
        severity: "low",
        affectedArea: "Lá, cổ bông và thân lúa",
        symptoms:
          "Vết bệnh hình thoi trên lá, cổ bông bị nâu, cây sinh trưởng chậm",
        treatment:
          "Cạo sạch vết bệnh, quét thuốc gốc đồng và xử lý nấm nấm đạo ôn",
        treatmentDate: "2023-12-08",
        recoveryStatus: "recovered",
        notes: "Đã khỏi hoàn toàn",
      },
    ],

    harvestHistory: [
      {
        id: "harv-014",
        date: "2023-11-10",
        quantity: 4800,
        quality: "B",
        price: 10000,
        totalRevenue: 48000000,
        buyer: "Công ty TNHH Lúa gạo Xuất khẩu",
      },
    ],
  },
  {
    id: "crop-015",
    code: "LUA-JAS85-015",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2018-11-20",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",

    regionId: 2,
    regionName: "Nông trại Lúa hữu cơ Đồng Tháp",
    areaId: 3,
    areaName: "Cánh đồng lúa VietGAP",
    plotId: "plot-2-1",
    plotName: "Lô 2-1 - Ruộng Lúa Jasmine 85",
    rowNumber: 2,
    coordinate: { lat: 10.968, lng: 107.226 },

    growthStage: "Mạ",
    expectedHarvestDate: "2019-03-19",
    actualAge: 3,

    certifications: [
      {
        id: "cert-015",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-12-01",
        expiryDate: "2025-12-01",
        certificateNumber: "ORG-VN-2023-456",
        status: "valid",
      },
    ],

    cultivationHistory: [
      {
        id: "cult-022",
        date: "2024-01-11",
        activity: "Bón phân",
        description: "Bón phân hữu cơ và NPK cân đối cho lúa Séng Cù",
        performedBy: "Hoàng Văn F",
        materials: "Phân hữu cơ vi sinh",
        quantity: "15kg/ruộng",
        cost: 60000,
      },
    ],

    diseaseHistory: [],

    harvestHistory: [],
  },
  {
    id: "crop-10-000",
    code: "LUA-JPN-016",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2018-06-06",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.525, lng: 108.045 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2018-10-04",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-001",
    code: "LUA-NH9-017",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2020-03-11",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 8,
    coordinate: { lat: 11.524047, lng: 108.046187 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2020-07-10",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-002",
    code: "LUA-OM18-018",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2018-06-24",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 1,
    coordinate: { lat: 11.522615, lng: 108.042614 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2018-10-24",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-003",
    code: "LUA-ST25-019",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2023-08-22",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.52798, lng: 108.044923 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2023-12-23",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-004",
    code: "LUA-OM5451-020",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2019-10-07",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.519495, lng: 108.045502 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2020-02-08",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-005",
    code: "LUA-JAS85-021",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2022-02-05",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.520247, lng: 108.048164 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2022-05-21",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-006",
    code: "LUA-JPN-022",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2019-01-13",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.526802, lng: 108.047753 },
    growthStage: "Mạ",
    expectedHarvestDate: "2019-04-29",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-007",
    code: "LUA-NH9-023",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2023-08-21",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 11,
    coordinate: { lat: 11.518379, lng: 108.049973 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2023-12-06",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-008",
    code: "LUA-OM18-024",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2022-03-01",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 7,
    coordinate: { lat: 11.526556, lng: 108.047038 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2022-06-17",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-009",
    code: "LUA-ST25-025",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2021-05-18",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.518056, lng: 108.043354 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2021-09-04",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-010",
    code: "LUA-OM5451-026",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2020-09-01",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 19,
    coordinate: { lat: 11.521993, lng: 108.046386 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2020-12-20",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-011",
    code: "LUA-JAS85-027",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2019-08-04",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.524258, lng: 108.043783 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2019-11-23",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-012",
    code: "LUA-JPN-028",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2021-05-16",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 11,
    coordinate: { lat: 11.519304, lng: 108.047283 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2021-09-05",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-013",
    code: "LUA-NH9-029",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2020-09-04",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.527991, lng: 108.042941 },
    growthStage: "Mạ",
    expectedHarvestDate: "2020-12-26",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-014",
    code: "LUA-OM18-030",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2021-09-07",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 8,
    coordinate: { lat: 11.52234, lng: 108.04412 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2021-12-30",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-015",
    code: "LUA-ST25-031",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2023-06-27",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.526375, lng: 108.045185 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2023-10-20",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-016",
    code: "LUA-OM5451-032",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2020-01-17",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.523737, lng: 108.040425 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2020-05-12",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-017",
    code: "LUA-JAS85-033",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2022-04-24",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.526224, lng: 108.046067 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2022-08-19",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-018",
    code: "LUA-JPN-034",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2023-08-23",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.524302, lng: 108.046642 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2023-12-19",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-019",
    code: "LUA-NH9-035",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2022-03-22",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.521467, lng: 108.041087 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2022-07-19",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-020",
    code: "LUA-OM18-036",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2018-09-03",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 10,
    coordinate: { lat: 11.521981, lng: 108.046461 },
    growthStage: "Mạ",
    expectedHarvestDate: "2019-01-01",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-021",
    code: "LUA-ST25-037",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2020-01-03",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 11,
    coordinate: { lat: 11.52663, lng: 108.044512 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2020-05-03",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-022",
    code: "LUA-OM5451-038",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2021-08-12",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.527499, lng: 108.04063 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2021-12-12",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-023",
    code: "LUA-JAS85-039",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2021-04-24",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 4,
    coordinate: { lat: 11.522808, lng: 108.049103 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2021-08-25",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-024",
    code: "LUA-JPN-040",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2023-01-23",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 15,
    coordinate: { lat: 11.51942, lng: 108.045174 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2023-05-27",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-025",
    code: "LUA-NH9-041",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2019-11-17",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.521285, lng: 108.047643 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2020-03-01",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-026",
    code: "LUA-OM18-042",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2020-09-25",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.523653, lng: 108.041587 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2021-01-09",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-027",
    code: "LUA-ST25-043",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2019-01-04",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.526468, lng: 108.04889 },
    growthStage: "Mạ",
    expectedHarvestDate: "2019-04-21",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-028",
    code: "LUA-OM5451-044",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2022-01-23",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.527147, lng: 108.048923 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2022-05-11",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-10-029",
    code: "LUA-JAS85-045",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2020-07-24",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 10,
    regionName: "Vùng Lúa Japonica Di Linh",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.522443, lng: 108.047801 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2020-11-10",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-000",
    code: "LUA-JPN-046",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2022-06-06",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.847289, lng: 108.539816 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2022-09-24",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-001",
    code: "LUA-NH9-047",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2023-02-22",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 7,
    coordinate: { lat: 11.84914, lng: 108.547693 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2023-06-13",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-002",
    code: "LUA-OM18-048",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2018-04-11",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.845667, lng: 108.543616 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2018-08-01",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-003",
    code: "LUA-ST25-049",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2018-12-20",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.843883, lng: 108.548493 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2019-04-12",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-004",
    code: "LUA-OM5451-050",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2018-12-22",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.849765, lng: 108.547102 },
    growthStage: "Mạ",
    expectedHarvestDate: "2019-04-15",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-005",
    code: "LUA-JAS85-051",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2021-03-22",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.847596, lng: 108.54532 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2021-07-15",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-006",
    code: "LUA-JPN-052",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2022-08-03",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.850274, lng: 108.54081 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2022-11-27",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-007",
    code: "LUA-NH9-053",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2019-06-20",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 10,
    coordinate: { lat: 11.848355, lng: 108.54195 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2019-10-15",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-008",
    code: "LUA-OM18-054",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2022-08-07",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 5,
    coordinate: { lat: 11.850321, lng: 108.548923 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2022-12-03",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-009",
    code: "LUA-ST25-055",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2023-03-12",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 4,
    coordinate: { lat: 11.844009, lng: 108.544908 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2023-07-09",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-010",
    code: "LUA-OM5451-056",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2021-07-23",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.848325, lng: 108.548521 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2021-11-20",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-011",
    code: "LUA-JAS85-057",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2021-03-18",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 19,
    coordinate: { lat: 11.843764, lng: 108.546178 },
    growthStage: "Mạ",
    expectedHarvestDate: "2021-07-17",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-012",
    code: "LUA-JPN-058",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2021-07-21",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 3,
    coordinate: { lat: 11.845498, lng: 108.54335 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2021-11-20",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-013",
    code: "LUA-NH9-059",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2020-03-07",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.845658, lng: 108.546332 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2020-07-08",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-014",
    code: "LUA-OM18-060",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2020-11-12",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.851698, lng: 108.544163 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2021-03-16",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-015",
    code: "LUA-ST25-061",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2021-11-22",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 16,
    coordinate: { lat: 11.852982, lng: 108.539104 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2022-03-07",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-016",
    code: "LUA-OM5451-062",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2018-02-18",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.85162, lng: 108.548966 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2018-06-04",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-017",
    code: "LUA-JAS85-063",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2020-03-26",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 4,
    coordinate: { lat: 11.850795, lng: 108.543557 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2020-07-11",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-018",
    code: "LUA-JPN-064",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2021-06-23",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.843081, lng: 108.548096 },
    growthStage: "Mạ",
    expectedHarvestDate: "2021-10-09",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-019",
    code: "LUA-NH9-065",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2020-07-19",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 18,
    coordinate: { lat: 11.84999, lng: 108.543555 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2020-11-05",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-020",
    code: "LUA-OM18-066",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2021-08-04",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 14,
    coordinate: { lat: 11.850315, lng: 108.546869 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2021-11-22",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-021",
    code: "LUA-ST25-067",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2019-06-01",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 3,
    coordinate: { lat: 11.851277, lng: 108.546229 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2019-09-20",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-022",
    code: "LUA-OM5451-068",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2019-08-08",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.851905, lng: 108.541828 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2019-11-28",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-023",
    code: "LUA-JAS85-069",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Vietnam.jpg",
    plantedDate: "2021-07-02",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 18,
    coordinate: { lat: 11.848831, lng: 108.544432 },
    growthStage: "Chín vàng",
    expectedHarvestDate: "2021-10-23",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-024",
    code: "LUA-JPN-070",
    name: "Lúa Japonica",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_fields_in_Tuy_Hoa.jpg",
    plantedDate: "2023-03-23",
    seedType: "Hạt giống Japonica chọn lọc",
    variety: "Japonica",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Japonica cho hạt gạo tròn, dẻo, phù hợp vùng canh tác kiểm soát nước tốt và quy trình chất lượng cao.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 9,
    coordinate: { lat: 11.844843, lng: 108.547302 },
    growthStage: "Thu hoạch",
    expectedHarvestDate: "2023-07-15",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-025",
    code: "LUA-NH9-071",
    name: "Lúa Nàng Hoa 9",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Japonica_Koshihikari.jpg",
    plantedDate: "2020-06-25",
    seedType: "Hạt giống Nàng Hoa 9",
    variety: "Nàng Hoa 9",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Nàng Hoa 9 là giống lúa thơm, chất lượng gạo tốt, cần theo dõi rầy nâu và đạo ôn trong giai đoạn đẻ nhánh.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 17,
    coordinate: { lat: 11.8482, lng: 108.54221 },
    growthStage: "Mạ",
    expectedHarvestDate: "2020-10-18",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-026",
    code: "LUA-OM18-072",
    name: "Lúa OM18",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Paddy_Field.jpg",
    plantedDate: "2018-03-26",
    seedType: "Hạt giống OM18 xác nhận",
    variety: "OM18",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM18 phù hợp sản xuất hàng hóa, có chất lượng gạo tốt và cần bón phân cân đối theo từng giai đoạn sinh trưởng.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 2,
    coordinate: { lat: 11.85091, lng: 108.547336 },
    growthStage: "Đẻ nhánh",
    expectedHarvestDate: "2018-07-20",
    actualAge: 4,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-027",
    code: "LUA-ST25-073",
    name: "Lúa ST25",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_1.jpg",
    plantedDate: "2023-04-13",
    seedType: "Hạt giống xác nhận ST25",
    variety: "ST25 Sóc Trăng",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa ST25 là giống lúa thơm chất lượng cao, cần quản lý nước và dinh dưỡng ổn định để đạt chất lượng gạo tốt.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 13,
    coordinate: { lat: 11.84678, lng: 108.541686 },
    growthStage: "Làm đòng",
    expectedHarvestDate: "2023-08-08",
    actualAge: 1,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-028",
    code: "LUA-OM5451-074",
    name: "Lúa OM5451",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/2024-11-23_Paddy_fields_in_Hoi_An_2.jpg",
    plantedDate: "2018-01-14",
    seedType: "Hạt giống cấp xác nhận 1",
    variety: "OM5451",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa OM5451 có khả năng thích nghi tốt, phù hợp canh tác tại đồng bằng sông Cửu Long và cho năng suất ổn định.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 6,
    coordinate: { lat: 11.84559, lng: 108.543455 },
    growthStage: "Trổ bông",
    expectedHarvestDate: "2018-05-12",
    actualAge: 2,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
  {
    id: "crop-11-029",
    code: "LUA-JAS85-075",
    name: "Lúa Jasmine 85",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Paddy_field_Viet_Nam.jpg",
    plantedDate: "2021-03-25",
    seedType: "Hạt giống lúa thơm Jasmine 85",
    variety: "Jasmine 85",
    groupCropName: "Cây lương thực (Rice Crops)",
    notes:
      "Lúa Jasmine 85 là giống lúa thơm, thích hợp canh tác theo hướng VietGAP và kiểm soát sâu bệnh IPM.",
    status: "healthy",
    regionId: 11,
    regionName: "Vùng Lúa chất lượng cao Cầu Đất",
    areaId: 0,
    areaName: "N/A",
    plotId: "",
    plotName: "N/A",
    rowNumber: 20,
    coordinate: { lat: 11.845355, lng: 108.541108 },
    growthStage: "Chín sữa",
    expectedHarvestDate: "2021-07-22",
    actualAge: 3,
    certifications: [],
    cultivationHistory: [],
    diseaseHistory: [],
    harvestHistory: [],
  },
];
export const GROWTH_STAGES = [
  { id: "seedling", name: "Giai đoạn cây con" },
  { id: "vegetative", name: "Sinh trưởng thân lá" },
  { id: "flowering", name: "Ra hoa" },
  { id: "fruiting", name: "Đậu quả" },
  { id: "ripening", name: "Quả chín" },
  { id: "harvesting", name: "Thu hoạch" },
];

export const ACTIVITY_TYPES = [
  { id: "watering", name: "Tưới nước" },
  { id: "fertilizing", name: "Bón phân" },
  { id: "pruning", name: "Cắt tỉa" },
  { id: "spraying", name: "Phun thuốc" },
  { id: "weeding", name: "Làm cỏ" },
  { id: "treatment", name: "Điều trị bệnh" },
  { id: "harvesting", name: "Thu hoạch" },
  { id: "other", name: "Khác" },
];

// Cultivation Zone (Vùng trồng) interfaces
export interface StaffMember {
  id: string;
  name: string;
  role: string; // Vai trò: Quản lý, Kỹ thuật viên, Công nhân
  phone: string;
  email?: string;
  assignedDate: string;
  specialization?: string; // Chuyên môn
}

export interface CropVariety {
  id: string;
  name: string; // Tên cây trồng
  variety: string; // Giống
  plantedDate: string;
  totalPlants: number; // Tổng số cây
  area: number; // Diện tích (ha)
  expectedYield: number; // Năng suất dự kiến (tấn/ha)
  status: "growing" | "flowering" | "harvesting" | "completed";
  seedType?: string; // Loại hạt giống
}

export interface CultivationPlan {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  status: "planned" | "in-progress" | "completed" | "cancelled";
  activities: {
    id: string;
    name: string;
    scheduledDate: string;
    completedDate?: string;
    assignedTo: string;
    status: "pending" | "in-progress" | "completed";
    notes?: string;
  }[];
  budget: number;
  actualCost?: number;
}

export interface CultivationZone {
  id: string;
  code: string;
  name: string;
  enterpriseId?: number; // ID doanh nghiệp
  location: string; // Địa chỉ
  province: string;
  district: string;
  ward?: string;
  totalArea: number; // Tổng diện tích (ha)
  cultivatedArea: number; // Diện tích canh tác (ha)
  coordinates: Coordinate[]; // Tọa độ bản đồ
  mapCenter: Coordinate;

  // Thông tin canh tác
  cropVarieties: CropVariety[];
  mainCrop: string; // Cây trồng chính
  soilType: string; // Loại đất
  irrigationSystem: string; // Hệ thống tưới

  // Nhân viên
  staff: StaffMember[];
  manager: string; // Người quản lý

  // Giấy chứng nhận
  certifications: Certification[];

  // Kế hoạch canh tác
  cultivationPlans: CultivationPlan[];

  // Thông tin khác
  establishedDate: string;
  status: "active" | "inactive" | "under-construction";
  notes: string;
}

export const MOCK_CULTIVATION_ZONES: CultivationZone[] = [
  {
    id: "zone-001",
    code: "ZONE-BP-001",
    name: "Vùng Sầu riêng Bình Phước",
    enterpriseId: 1,
    location: "Khu phố 3, Phường Tân Đồng, TP Đồng Xoài",
    province: "Bình Phước",
    district: "Bù Đăng",
    ward: "Xã Đức Liễu",
    totalArea: 50.5,
    cultivatedArea: 48.2,
    coordinates: [
      { lat: 11.53, lng: 106.88 },
      { lat: 11.53, lng: 106.91 },
      { lat: 11.55, lng: 106.91 },
      { lat: 11.55, lng: 106.88 },
    ],
    mapCenter: { lat: 11.54, lng: 106.895 },

    cropVarieties: [
      {
        id: "cv-001",
        name: "Sầu riêng",
        variety: "Dona Malaysia",
        plantedDate: "2020-05-15",
        totalPlants: 850,
        area: 25.5,
        expectedYield: 12,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
      {
        id: "cv-002",
        name: "Sầu riêng",
        variety: "Ri6 Thái Lan",
        plantedDate: "2019-11-20",
        totalPlants: 720,
        area: 18.2,
        expectedYield: 15,
        status: "harvesting",
        seedType: "Hạt giống F1",
      },
      {
        id: "cv-003",
        name: "Sầu riêng",
        variety: "Monthong",
        plantedDate: "2018-03-25",
        totalPlants: 180,
        area: 4.5,
        expectedYield: 18,
        status: "harvesting",
        seedType: "Hạt giống F1",
      },
    ],
    mainCrop: "Sầu riêng",
    soilType: "Đất đỏ Bazan",
    irrigationSystem: "Tưới nhỏ giọt tự động",

    staff: [
      {
        id: "staff-001",
        name: "Nguyễn Văn A",
        role: "Quản lý vùng",
        phone: "0901234567",
        email: "nguyenvana@example.com",
        assignedDate: "2020-01-15",
        specialization: "Kỹ thuật trồng sầu riêng",
      },
      {
        id: "staff-002",
        name: "Trần Văn B",
        role: "Kỹ thuật viên",
        phone: "0912345678",
        email: "tranvanb@example.com",
        assignedDate: "2020-03-01",
        specialization: "Bảo vệ thực vật",
      },
      {
        id: "staff-003",
        name: "Lê Thị C",
        role: "Kỹ thuật viên",
        phone: "0923456789",
        assignedDate: "2020-06-10",
        specialization: "Dinh dưỡng cây trồng",
      },
      {
        id: "staff-004",
        name: "Phạm Văn D",
        role: "Trưởng nhóm công nhân",
        phone: "0934567890",
        assignedDate: "2020-02-01",
      },
    ],
    manager: "Nguyễn Văn A",

    certifications: [
      {
        id: "cert-zone-001",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Bình Phước",
        issueDate: "2023-01-10",
        expiryDate: "2025-01-10",
        certificateNumber: "VG-BP-2023-001",
        status: "valid",
      },
      {
        id: "cert-zone-002",
        name: "GlobalGAP",
        issuer: "SGS Vietnam",
        issueDate: "2023-06-01",
        expiryDate: "2025-06-01",
        certificateNumber: "GG-VN-2023-089",
        status: "valid",
      },
    ],

    cultivationPlans: [
      {
        id: "plan-001",
        name: "Kế hoạch canh tác Quý 1/2024",
        startDate: "2024-01-01",
        endDate: "2024-03-31",
        status: "in-progress",
        budget: 150000000,
        actualCost: 85000000,
        activities: [
          {
            id: "act-001",
            name: "Bón phân lần 1",
            scheduledDate: "2024-01-15",
            completedDate: "2024-01-15",
            assignedTo: "Lê Thị C",
            status: "completed",
            notes: "Đã hoàn thành đúng kế hoạch",
          },
          {
            id: "act-002",
            name: "Phun thuốc phòng bệnh",
            scheduledDate: "2024-02-01",
            completedDate: "2024-02-02",
            assignedTo: "Trần Văn B",
            status: "completed",
          },
          {
            id: "act-003",
            name: "Cắt tỉa cành",
            scheduledDate: "2024-02-15",
            assignedTo: "Phạm Văn D",
            status: "in-progress",
          },
          {
            id: "act-004",
            name: "Bón phân lần 2",
            scheduledDate: "2024-03-15",
            assignedTo: "Lê Thị C",
            status: "pending",
          },
        ],
      },
      {
        id: "plan-002",
        name: "Kế hoạch thu hoạch 2024",
        startDate: "2024-04-01",
        endDate: "2024-08-31",
        status: "planned",
        budget: 200000000,
        activities: [
          {
            id: "act-005",
            name: "Thu hoạch đợt 1 - Ri6",
            scheduledDate: "2024-04-15",
            assignedTo: "Phạm Văn D",
            status: "pending",
          },
          {
            id: "act-006",
            name: "Thu hoạch đợt 2 - Monthong",
            scheduledDate: "2024-05-20",
            assignedTo: "Phạm Văn D",
            status: "pending",
          },
        ],
      },
    ],

    establishedDate: "2019-10-01",
    status: "active",
    notes:
      "Vùng trồng thử nghiệm sầu riêng chất lượng cao, áp dụng công nghệ tưới tiên tiến",
  },
  {
    id: "zone-002",
    code: "ZONE-DN-001",
    name: "Nông trại Hữu cơ Đồng Nai",
    enterpriseId: 2,
    location: "Xã Gia Kiệm, Huyện Thống Nhất",
    province: "Đồng Nai",
    district: "Định Quán",
    ward: "Xã Phụ Ngọc",
    totalArea: 120.0,
    cultivatedArea: 115.5,
    coordinates: [
      { lat: 10.957, lng: 107.22 },
      { lat: 10.957, lng: 107.23 },
      { lat: 10.965, lng: 107.23 },
      { lat: 10.965, lng: 107.22 },
    ],
    mapCenter: { lat: 10.961, lng: 107.225 },

    cropVarieties: [
      {
        id: "cv-004",
        name: "Xoài",
        variety: "Cát Hòa Lộc",
        plantedDate: "2020-12-05",
        totalPlants: 1200,
        area: 40.0,
        expectedYield: 8,
        status: "growing",
        seedType: "Cây thực sinh",
      },
      {
        id: "cv-005",
        name: "Thanh long",
        variety: "Ruột đỏ",
        plantedDate: "2022-01-20",
        totalPlants: 2500,
        area: 35.5,
        expectedYield: 20,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
      {
        id: "cv-006",
        name: "Nhãn",
        variety: "Ido Thái Lan",
        plantedDate: "2019-10-05",
        totalPlants: 800,
        area: 25.0,
        expectedYield: 10,
        status: "harvesting",
        seedType: "Hạt giống F1",
      },
      {
        id: "cv-007",
        name: "Chôm chôm",
        variety: "Chôm chôm Nhãn",
        plantedDate: "2020-04-12",
        totalPlants: 450,
        area: 15.0,
        expectedYield: 7,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
    ],
    mainCrop: "Rau màu hữu cơ",
    soilType: "Đất phù sa",
    irrigationSystem: "Tưới phun mưa",

    staff: [
      {
        id: "staff-005",
        name: "Hoàng Văn E",
        role: "Quản lý vùng",
        phone: "0945678901",
        email: "hoangvane@example.com",
        assignedDate: "2019-08-01",
        specialization: "Nông nghiệp hữu cơ",
      },
      {
        id: "staff-006",
        name: "Võ Văn F",
        role: "Kỹ thuật viên",
        phone: "0956789012",
        assignedDate: "2020-01-15",
        specialization: "Trồng trọt hữu cơ",
      },
      {
        id: "staff-007",
        name: "Đặng Thị G",
        role: "Kỹ thuật viên",
        phone: "0967890123",
        assignedDate: "2020-05-20",
        specialization: "Kiểm soát chất lượng",
      },
    ],
    manager: "Hoàng Văn E",

    certifications: [
      {
        id: "cert-zone-003",
        name: "Organic Certificate",
        issuer: "Control Union Vietnam",
        issueDate: "2023-08-01",
        expiryDate: "2025-08-01",
        certificateNumber: "ORG-VN-2023-167",
        status: "valid",
      },
      {
        id: "cert-zone-004",
        name: "VietGAP",
        issuer: "Sở Nông nghiệp Đồng Nai",
        issueDate: "2023-06-15",
        expiryDate: "2025-06-15",
        certificateNumber: "VG-DN-2023-089",
        status: "valid",
      },
    ],

    cultivationPlans: [
      {
        id: "plan-003",
        name: "Kế hoạch canh tác hữu cơ 2024",
        startDate: "2024-01-01",
        endDate: "2024-12-31",
        status: "in-progress",
        budget: 300000000,
        actualCost: 120000000,
        activities: [
          {
            id: "act-007",
            name: "Bón phân hữu cơ",
            scheduledDate: "2024-01-20",
            completedDate: "2024-01-20",
            assignedTo: "Võ Văn F",
            status: "completed",
          },
          {
            id: "act-008",
            name: "Kiểm tra chất lượng đất",
            scheduledDate: "2024-02-10",
            completedDate: "2024-02-11",
            assignedTo: "Đặng Thị G",
            status: "completed",
          },
          {
            id: "act-009",
            name: "Phun thuốc sinh học",
            scheduledDate: "2024-03-01",
            assignedTo: "Võ Văn F",
            status: "pending",
          },
        ],
      },
    ],

    establishedDate: "2019-05-15",
    status: "active",
    notes: "Nông trại chuyên canh rau màu hữu cơ theo tiêu chuẩn quốc tế",
  },
  {
    id: "zone-003",
    code: "ZONE-DL-001",
    name: "Đồi Cà phê Buôn Ma Thuột",
    enterpriseId: 4,
    location: "Km 15, Quốc lộ 14, TP Buôn Ma Thuột",
    province: "Lâm Đồng",
    district: "Bảo Lộc",
    ward: "Phường Lộc Tiến",
    totalArea: 200.5,
    cultivatedArea: 195.0,
    coordinates: [
      { lat: 12.667, lng: 108.037 },
      { lat: 12.667, lng: 108.05 },
      { lat: 12.68, lng: 108.05 },
      { lat: 12.68, lng: 108.037 },
    ],
    mapCenter: { lat: 12.6735, lng: 108.0435 },

    cropVarieties: [
      {
        id: "cv-008",
        name: "Cà phê",
        variety: "Robusta Đắk Lắk",
        plantedDate: "2020-08-15",
        totalPlants: 15000,
        area: 150.0,
        expectedYield: 2.5,
        status: "flowering",
        seedType: "Cây giống ghép",
      },
      {
        id: "cv-009",
        name: "Cà phê",
        variety: "Arabica Cầu Đất",
        plantedDate: "2021-02-20",
        totalPlants: 5000,
        area: 45.0,
        expectedYield: 1.8,
        status: "growing",
        seedType: "Cây thực sinh",
      },
    ],
    mainCrop: "Cà phê Robusta",
    soilType: "Đất đỏ Bazan",
    irrigationSystem: "Tưới nhỏ giọt",

    staff: [
      {
        id: "staff-008",
        name: "Nguyễn Văn H",
        role: "Quản lý vùng",
        phone: "0978901234",
        email: "nguyenvanh@example.com",
        assignedDate: "2020-06-01",
        specialization: "Kỹ thuật trồng cà phê",
      },
      {
        id: "staff-009",
        name: "Lê Văn I",
        role: "Kỹ thuật viên",
        phone: "0989012345",
        assignedDate: "2020-08-01",
        specialization: "Chế biến cà phê",
      },
      {
        id: "staff-010",
        name: "Trần Thị K",
        role: "Kỹ thuật viên",
        phone: "0990123456",
        assignedDate: "2021-01-10",
        specialization: "Bảo vệ thực vật",
      },
    ],
    manager: "Nguyễn Văn H",

    certifications: [
      {
        id: "cert-zone-005",
        name: "Rainforest Alliance",
        issuer: "Rainforest Alliance",
        issueDate: "2023-04-01",
        expiryDate: "2026-04-01",
        certificateNumber: "RA-VN-2023-156",
        status: "valid",
      },
      {
        id: "cert-zone-006",
        name: "UTZ Certified",
        issuer: "UTZ Vietnam",
        issueDate: "2023-05-10",
        expiryDate: "2025-05-10",
        certificateNumber: "UTZ-2023-789",
        status: "valid",
      },
    ],

    cultivationPlans: [
      {
        id: "plan-004",
        name: "Kế hoạch thu hoạch cà phê 2024",
        startDate: "2024-10-01",
        endDate: "2024-12-31",
        status: "planned",
        budget: 500000000,
        activities: [
          {
            id: "act-010",
            name: "Chuẩn bị thu hoạch",
            scheduledDate: "2024-10-01",
            assignedTo: "Lê Văn I",
            status: "pending",
          },
          {
            id: "act-011",
            name: "Thu hoạch đợt 1",
            scheduledDate: "2024-11-01",
            assignedTo: "Nguyễn Văn H",
            status: "pending",
          },
        ],
      },
    ],

    establishedDate: "2020-05-01",
    status: "active",
    notes: "Vùng cà phê xuất khẩu chất lượng cao, áp dụng quy trình bền vững",
  },
];
