import type { TreatmentProtocol } from "./types";

export const mockProtocols: TreatmentProtocol[] = [
  {
    id: "1",
    name: "Đạo ôn lá lúa (Cháy lá)",
    code: "LUA-DAOON-01",
    crop: "LÚA",
    location: "ĐỂ NHÁNH - LÂM ĐỒNG",
    diseaseName: "Bệnh đạo ôn",
    diseaseScientificName: "Pyricularia oryzae",
    diseaseType: "nấm",
    symptoms: [
      "Vết bệnh hình thoi, tâm xám trắng",
      "Xuất hiện rải rác trên lá",
      "Lá bị cháy khô khi nặng",
    ],
    condition: "Ẩm độ cao, sương mù dày",
    status: "active",
    severity: "TRUNG-BINH",
    duration: 7,
    costPerHa: "650.000 đ/ha",
    expert: {
      name: "Ths. Nguyễn Văn An",
      title: "Chuyên gia BVTV",
      avatar: "https://i.pravatar.cc/150?u=nva",
    },
    medicines: [
      {
        id: "m1",
        name: "Tricyclazole 75WP",
        type: "TRỪ NẤM",
        dosage: "20g/25L",
        unit: "g",
      },
      {
        id: "m2",
        name: "Isoprothiolane 40EC",
        type: "TRỪ NẤM",
        dosage: "50ml/25L",
        unit: "ml",
      },
    ],
    steps: [
      {
        id: "s1",
        day: 1,
        title: "Cắt nguồn bệnh",
        description: "Rút nước cạn, ngưng bón đạm.",
      },
      {
        id: "s2",
        day: 3,
        title: "Phun thuốc đặc trị",
        description: "Phun ướt đều tán lá vào sáng sớm.",
        medicineId: "m1",
      },
      {
        id: "s3",
        day: 5,
        title: "Bón phân phục hồi",
        description: "Bổ sung Kali Silic giúp cứng cây.",
      },
    ],
    safetyNotes: [
      "Trang bị đồ bảo hộ khi phun thuốc",
      "Thời gian cách ly: 7 ngày",
      "Không phun khi trời sắp mưa",
    ],
    image:
      "https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "2",
    name: "Rầy nâu hại lúa",
    code: "LUA-RAYNAU-02",
    crop: "LÚA",
    location: "TRỔ BÔNG - TIỀN GIANG",
    diseaseName: "Rầy nâu",
    diseaseScientificName: "Nilaparvata lugens",
    diseaseType: "côn trùng",
    symptoms: ["Cây héo khô (cháy rầy)", "Sự xuất hiện của nấm muội đen"],
    condition: "Nhiệt độ 25-30°C, ẩm độ cao",
    status: "active",
    severity: "CAO",
    duration: 5,
    costPerHa: "800.000 đ/ha",
    expert: {
      name: "Ths. Lê Thị Bình",
      title: "Chuyên gia Côn trùng",
      avatar: "https://i.pravatar.cc/150?u=ltb",
    },
    medicines: [
      {
        id: "m3",
        name: "Pymetrozine 50WG",
        type: "TRỪ RẦY",
        dosage: "10g/25L",
        unit: "g",
      },
    ],
    steps: [
      {
        id: "s1",
        day: 1,
        title: "Kiểm tra mật độ",
        description: "Xác định mật độ rầy trên gốc lúa.",
      },
      {
        id: "s2",
        day: 2,
        title: "Xử lý thuốc",
        description: "Phun đều vào gốc lúa.",
        medicineId: "m3",
      },
    ],
    safetyNotes: ["Thời gian cách ly: 14 ngày"],
    image:
      "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "3",
    name: "Sâu keo mùa thu hại Ngô",
    code: "NGO-SAUKEO-01",
    crop: "BẮP (NGÔ)",
    location: "8 LÁ - ĐẮK LẮK",
    diseaseName: "Sâu keo mùa thu",
    diseaseScientificName: "Spodoptera frugiperda",
    diseaseType: "sâu hại",
    symptoms: ["Vết ăn thủng lá", "Lỗ hổng lớn trên phiến lá"],
    condition: "Thời tiết ấm và ẩm",
    status: "active",
    severity: "CAO",
    duration: 10,
    costPerHa: "1.200.000 đ/ha",
    expert: {
      name: "Trần Văn Cường",
      title: "Chuyên gia BVTV",
      avatar: "https://i.pravatar.cc/150?u=tvc",
    },
    medicines: [],
    steps: [],
    safetyNotes: [],
    image:
      "https://images.unsplash.com/photo-1595231712423-997579730248?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "4",
    name: "Nứt thân xì mủ Sầu riêng",
    code: "SR-NUTTHAN-01",
    crop: "SẦU RIÊNG",
    location: "KINH DOANH - BÌNH PHƯỚC",
    diseaseName: "Thối gốc chảy nhựa",
    diseaseScientificName: "Phytophthora palmivora",
    diseaseType: "nấm",
    symptoms: ["Vết nứt chảy nhựa", "Rễ bị thối đen"],
    condition: "Thoát nước kém",
    status: "active",
    severity: "CAO",
    duration: 30,
    costPerHa: "2.500.000 đ/ha",
    expert: {
      name: "Nguyễn Văn An",
      title: "Chuyên gia Cây ăn trái",
      avatar: "https://i.pravatar.cc/150?u=nva",
    },
    medicines: [],
    steps: [],
    safetyNotes: [],
    image:
      "https://images.unsplash.com/photo-1596708051111-9257d079639e?q=80&w=400&auto=format&fit=crop",
  },
];
