import type { GroupCrop } from "./types";

export const initialData: GroupCrop[] = [
  {
    id: 1,
    code: "rice",
    name: "Lúa",
    scientificName: "Oryza sativa",
    category: "Lương thực",
    description: "Cây lương thực chính tại Việt Nam.",
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    code: "corn",
    name: "Bắp (Ngô)",
    scientificName: "Zea mays",
    category: "Lương thực",
    description: "Cây lương thực phổ biến.",
    createdAt: "2024-01-11",
  },
  {
    id: 3,
    code: "soybean",
    name: "Đậu nành",
    scientificName: "Glycine max",
    category: "Hạt",
    description: "Cây họ đậu ngắn ngày, giàu đạm.",
    createdAt: "2024-01-12",
  },
  {
    id: 4,
    code: "cassava",
    name: "Khoai mì",
    scientificName: "Manihot esculenta",
    category: "Lương thực",
    description: "Cây dễ trồng, chịu hạn tốt.",
    createdAt: "2024-01-13",
  },
  {
    id: 5,
    code: "sweet_potato",
    name: "Khoai lang",
    scientificName: "Ipomoea batatas",
    category: "Lương thực",
    description: "Cây trồng ngắn ngày, thích hợp đất cát.",
    createdAt: "2024-01-14",
  },
  {
    id: 6,
    code: "sugarcane",
    name: "Mía",
    scientificName: "Saccharum officinarum",
    category: "Cây công nghiệp",
    description: "Nguyên liệu sản xuất đường.",
    createdAt: "2024-01-15",
  },
  {
    id: 7,
    code: "coffee",
    name: "Cà phê",
    scientificName: "Coffea",
    category: "Cây công nghiệp",
    description: "Cây công nghiệp dài ngày.",
    createdAt: "2024-01-16",
  },
  {
    id: 8,
    code: "rubber",
    name: "Cao su",
    scientificName: "Hevea brasiliensis",
    category: "Cây công nghiệp",
    description: "Cây lấy mủ công nghiệp.",
    createdAt: "2024-01-17",
  },
  {
    id: 9,
    code: "tea",
    name: "Chè",
    scientificName: "Camellia sinensis",
    category: "Cây công nghiệp",
    description: "Cây công nghiệp và dược liệu.",
    createdAt: "2024-01-18",
  },
  {
    id: 10,
    code: "pepper",
    name: "Hồ tiêu",
    scientificName: "Piper nigrum",
    category: "Cây gia vị",
    description: "Gia vị quan trọng, xuất khẩu nhiều.",
    createdAt: "2024-01-19",
  },
];
