export const MASTER_DATA_BASE_PATH = "/api/admin/master-data" as const;

export const MASTER_DATA_PATHS = {
  base: MASTER_DATA_BASE_PATH,
  banks: `${MASTER_DATA_BASE_PATH}/banks`,
  businessLines: `${MASTER_DATA_BASE_PATH}/business-lines`,
  certificateIssuers: `${MASTER_DATA_BASE_PATH}/certificate-issuers`,
  certificateStandards: `${MASTER_DATA_BASE_PATH}/certificate-standards`,
  organizationTypes: `${MASTER_DATA_BASE_PATH}/organization-types`,
  geoProvinces: `${MASTER_DATA_BASE_PATH}/geo/provinces`,
  geoWards: `${MASTER_DATA_BASE_PATH}/geo/wards`,
  equipmentToolGroups: `${MASTER_DATA_BASE_PATH}/equipment-tool-groups`,
  fertilizerGroups: `${MASTER_DATA_BASE_PATH}/fertilizer-groups`,
  irrigationSystems: `${MASTER_DATA_BASE_PATH}/irrigation-systems`,
  rearingMethods: `${MASTER_DATA_BASE_PATH}/rearing-methods`,
  materialGroups: `${MASTER_DATA_BASE_PATH}/material-groups`,
  pesticideGroups: `${MASTER_DATA_BASE_PATH}/pesticide-groups`,
  pesticideOrigins: `${MASTER_DATA_BASE_PATH}/pesticide-origins`,
  pesticideToxicityClasses: `${MASTER_DATA_BASE_PATH}/pesticide-toxicity-classes`,
  livestockMedicineFunctions: `${MASTER_DATA_BASE_PATH}/livestock-medicine-functions`,
  livestockMedicineAdministrationRoutes: `${MASTER_DATA_BASE_PATH}/livestock-medicine-administration-routes`,
  livestockMedicineControlLevels: `${MASTER_DATA_BASE_PATH}/livestock-medicine-control-levels`,
  aquacultureMedicineFunctions: `${MASTER_DATA_BASE_PATH}/aquaculture-medicine-functions`,
  aquacultureMedicineTargetSpecies: `${MASTER_DATA_BASE_PATH}/aquaculture-medicine-target-species`,
  aquacultureMedicineControlResidues: `${MASTER_DATA_BASE_PATH}/aquaculture-medicine-control-residues`,
  planGroups: `${MASTER_DATA_BASE_PATH}/plan-groups`,
  planTypes: `${MASTER_DATA_BASE_PATH}/plan-types`,
  vsicIndustries: `${MASTER_DATA_BASE_PATH}/vsic-industries`,
} as const;

export const MASTER_DATA_CATALOGS = [
  "banks",
  "business-lines",
  "departments",
  "equipment-tool-groups",
  "fertilizer-groups",
  "irrigation-systems",
  "rearing-methods",
  "iot-device-groups",
  "material-groups",
  "pesticide-groups",
  "pesticide-origins",
  "pesticide-toxicity-classes",
  "livestock-medicine-functions",
  "livestock-medicine-administration-routes",
  "livestock-medicine-control-levels",
  "aquaculture-medicine-functions",
  "aquaculture-medicine-target-species",
  "aquaculture-medicine-control-residues",
  "plan-groups",
  "plan-types",
  "position-groups",
  "positions",
  "certificate-issuers",
  "certificate-standards",
  "organization-types",
  "vsic-industries",
] as const;

export type MasterDataCatalog = (typeof MASTER_DATA_CATALOGS)[number];
