import type { CultivationRegion } from "../../../stores/useCultivationRegionStore";
import type { Region } from "../../region-chart/constants";

export const mockSearchZoneEnterprises = [
  {
    id: "ent-eco-durian",
    code: "ECO-DUR",
    name: "Công ty TNHH Nông nghiệp Xanh Bình Phước",
    brandName: "EcoDurian Bình Phước",
    image: "/company.jpg",
    address: "Xã Đức Liễu, huyện Bù Đăng, Bình Phước",
    phone: "0271 388 8801",
    email: "ops@ecodurian.vn",
  },
  {
    id: "ent-mekong",
    code: "MKG-FARM",
    name: "HTX Nông nghiệp Mekong Fresh",
    brandName: "Mekong Fresh",
    image: "/cooperative.jpg",
    address: "Xã Mỹ Đông, huyện Tháp Mười, Đồng Tháp",
    phone: "0277 366 9090",
    email: "farm@mekongfresh.vn",
  },
  {
    id: "ent-highland",
    code: "HGL-AGRI",
    name: "Công ty CP Cao nguyên Hữu cơ",
    brandName: "Highland Organic",
    image: "/farmer.jpg",
    address: "Xã Ea Tu, TP. Buôn Ma Thuột, Đắk Lắk",
    phone: "0262 355 1200",
    email: "hello@highlandorganic.vn",
  },
];

export const mockSearchZoneRegions: Region[] = [
  {
    id: 9101,
    code: "REG-BP-01",
    name: "Vùng sầu riêng Đức Liễu",
    provinceId: "Bình Phước",
    districtId: "Bù Đăng",
    ward: "Đức Liễu",
    address: "Ấp 3, xã Đức Liễu, huyện Bù Đăng",
    enterpriseId: "ent-eco-durian",
    area: 126.8,
    landType: "DAT002",
    terrain: "DH002",
    note: "Vùng chuyên canh sầu riêng xuất khẩu, tưới nhỏ giọt và nhật ký QR theo từng lô.",
    status: "active",
    createdAt: "2026-01-12",
    coordinates: [
      { lat: 11.714, lng: 107.209 },
      { lat: 11.724, lng: 107.224 },
      { lat: 11.715, lng: 107.241 },
      { lat: 11.699, lng: 107.229 },
    ],
    cropVarieties: [
      {
        id: "crop-bp-ri6",
        name: "Sầu riêng",
        variety: "Ri6",
        status: "harvesting",
        plantedDate: "2021-04-18",
        seedType: "Cây giống ghép",
      },
      {
        id: "crop-bp-mk",
        name: "Sầu riêng",
        variety: "Musang King",
        status: "flowering",
        plantedDate: "2022-02-10",
        seedType: "Cây giống ghép tuyển chọn",
      },
    ],
    subAreas: [
      {
        id: "area-bp-a",
        code: "AREA-BP-A",
        name: "Khu A - Ri6 xuất khẩu",
        regionId: 9101,
        area: 46.2,
        landType: "DAT002",
        terrain: "DH002",
        status: "active",
        createdAt: "2026-01-14",
        coordinates: [
          { lat: 11.714, lng: 107.209 },
          { lat: 11.721, lng: 107.219 },
          { lat: 11.713, lng: 107.228 },
          { lat: 11.705, lng: 107.218 },
        ],
        plots: [
          {
            id: "plot-bp-a1",
            code: "PLOT-BP-A1",
            name: "Lô A1 - Ri6 36 tháng",
            area: 18.4,
            altitude: 162,
            contour: "160m",
            coordinates: [
              { lat: 11.714, lng: 107.209 },
              { lat: 11.718, lng: 107.215 },
              { lat: 11.713, lng: 107.221 },
              { lat: 11.708, lng: 107.215 },
            ],
          },
          {
            id: "plot-bp-a2",
            code: "PLOT-BP-A2",
            name: "Lô A2 - Ri6 VietGAP",
            area: 27.8,
            altitude: 158,
            contour: "155m",
            coordinates: [
              { lat: 11.718, lng: 107.215 },
              { lat: 11.721, lng: 107.219 },
              { lat: 11.713, lng: 107.228 },
              { lat: 11.713, lng: 107.221 },
            ],
          },
        ],
      },
      {
        id: "area-bp-b",
        code: "AREA-BP-B",
        name: "Khu B - Musang King",
        regionId: 9101,
        area: 38.6,
        landType: "DAT002",
        terrain: "DH002",
        status: "active",
        createdAt: "2026-01-18",
        coordinates: [
          { lat: 11.721, lng: 107.219 },
          { lat: 11.724, lng: 107.224 },
          { lat: 11.715, lng: 107.241 },
          { lat: 11.713, lng: 107.228 },
        ],
        plots: [
          {
            id: "plot-bp-b1",
            code: "PLOT-BP-B1",
            name: "Lô B1 - Musang King",
            area: 20.1,
            altitude: 166,
            contour: "165m",
            coordinates: [
              { lat: 11.721, lng: 107.219 },
              { lat: 11.724, lng: 107.224 },
              { lat: 11.719, lng: 107.233 },
              { lat: 11.715, lng: 107.227 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 9201,
    code: "REG-DT-01",
    name: "Cánh đồng lúa thông minh Tháp Mười",
    provinceId: "Đồng Tháp",
    districtId: "Tháp Mười",
    ward: "Mỹ Đông",
    address: "Cụm sản xuất số 2, xã Mỹ Đông",
    enterpriseId: "ent-mekong",
    area: 214.5,
    landType: "DAT001",
    terrain: "DH001",
    note: "Vùng lúa chất lượng cao, quản lý nước tự động và giám sát sâu bệnh bằng bẫy đèn.",
    status: "active",
    createdAt: "2026-02-03",
    coordinates: [
      { lat: 10.557, lng: 105.832 },
      { lat: 10.571, lng: 105.845 },
      { lat: 10.562, lng: 105.866 },
      { lat: 10.544, lng: 105.852 },
    ],
    cropVarieties: [
      {
        id: "crop-dt-st25",
        name: "Lúa",
        variety: "ST25",
        status: "vegetative",
        plantedDate: "2026-08-05",
        seedType: "Giống xác nhận",
      },
    ],
    subAreas: [
      {
        id: "area-dt-a",
        code: "AREA-DT-A",
        name: "Ô sản xuất ST25",
        regionId: 9201,
        area: 88.4,
        landType: "DAT001",
        terrain: "DH001",
        status: "active",
        createdAt: "2026-02-08",
        coordinates: [
          { lat: 10.557, lng: 105.832 },
          { lat: 10.568, lng: 105.842 },
          { lat: 10.559, lng: 105.855 },
          { lat: 10.55, lng: 105.845 },
        ],
        plots: [
          {
            id: "plot-dt-a1",
            code: "PLOT-DT-A1",
            name: "Ruộng A1 - ST25",
            area: 44.2,
            altitude: 3,
            contour: "3m",
            coordinates: [
              { lat: 10.557, lng: 105.832 },
              { lat: 10.563, lng: 105.837 },
              { lat: 10.555, lng: 105.848 },
              { lat: 10.55, lng: 105.845 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 9301,
    code: "REG-DL-01",
    name: "Vùng cà phê hữu cơ Ea Tu",
    provinceId: "Đắk Lắk",
    districtId: "Buôn Ma Thuột",
    ward: "Ea Tu",
    address: "Buôn Ko Tam, xã Ea Tu",
    enterpriseId: "ent-highland",
    area: 98.7,
    landType: "DAT002",
    terrain: "DH003",
    note: "Vùng cà phê Robusta hữu cơ xen canh hồ tiêu và cây che bóng.",
    status: "inactive",
    createdAt: "2025-11-20",
    coordinates: [
      { lat: 12.726, lng: 108.103 },
      { lat: 12.739, lng: 108.112 },
      { lat: 12.731, lng: 108.132 },
      { lat: 12.715, lng: 108.121 },
    ],
    cropVarieties: [
      {
        id: "crop-dl-robusta",
        name: "Cà phê",
        variety: "Robusta TRS1",
        status: "maintenance",
        plantedDate: "2020-06-12",
        seedType: "Cây giống thực sinh chọn lọc",
      },
    ],
    subAreas: [
      {
        id: "area-dl-a",
        code: "AREA-DL-A",
        name: "Khu cà phê xen tiêu",
        regionId: 9301,
        area: 52.3,
        landType: "DAT002",
        terrain: "DH003",
        status: "inactive",
        createdAt: "2025-11-24",
        coordinates: [
          { lat: 12.726, lng: 108.103 },
          { lat: 12.735, lng: 108.111 },
          { lat: 12.729, lng: 108.122 },
          { lat: 12.719, lng: 108.116 },
        ],
        plots: [
          {
            id: "plot-dl-a1",
            code: "PLOT-DL-A1",
            name: "Lô cà phê A1",
            area: 24.6,
            altitude: 522,
            contour: "520m",
            coordinates: [
              { lat: 12.726, lng: 108.103 },
              { lat: 12.731, lng: 108.108 },
              { lat: 12.726, lng: 108.116 },
              { lat: 12.719, lng: 108.111 },
            ],
          },
        ],
      },
    ],
  },
];

export const mockSearchZoneCultivationRegions: CultivationRegion[] = [
  {
    id: "mock-zone-bp-export",
    name: "Vùng canh tác sầu riêng xuất khẩu Bình Phước",
    scope: "region",
    targetIds: ["9101"],
    targetName: "Vùng sầu riêng Đức Liễu",
    enterpriseId: "ent-eco-durian",
    certificateIds: ["VietGAP", "GlobalGAP", "Mã vùng trồng CN-09101"],
    managerIds: ["Nguyễn Văn Phú", "Trần Thị Mai"],
    note: "Mock chi tiết đầy đủ: sầu riêng Ri6 và Musang King, nhật ký canh tác số, truy xuất QR theo lô.",
    farmingMethodId: "organic",
    irrigationMethodId: "drip",
    selectedCrops: ["Sầu riêng Ri6", "Sầu riêng Musang King"],
    status: "active",
    createdAt: "2026-01-20",
  },
  {
    id: "mock-zone-bp-area",
    name: "Khu canh tác Ri6 VietGAP",
    scope: "area",
    targetIds: ["area-bp-a", "plot-bp-a2"],
    targetName: "Khu A - Ri6 xuất khẩu, Lô A2 - Ri6 VietGAP",
    enterpriseId: "ent-eco-durian",
    certificateIds: ["VietGAP", "HACCP"],
    managerIds: ["Lê Quốc Huy"],
    note: "Khu theo dõi riêng phục vụ đơn hàng xuất khẩu tháng 10/2026.",
    farmingMethodId: "vietgap",
    irrigationMethodId: "drip",
    selectedCrops: ["Sầu riêng Ri6"],
    status: "active",
    createdAt: "2026-03-11",
  },
  {
    id: "mock-zone-dt-rice",
    name: "Vùng lúa thông minh ST25 Tháp Mười",
    scope: "area",
    targetIds: ["area-dt-a"],
    targetName: "Ô sản xuất ST25",
    enterpriseId: "ent-mekong",
    certificateIds: ["SRP", "VietGAP", "OCOP 4 sao"],
    managerIds: ["Phạm Minh Tâm", "Võ Thị Lan"],
    note: "Vùng mock lúa ST25 có dữ liệu bẫy đèn, mực nước và lịch phun phòng bệnh đạo ôn.",
    farmingMethodId: "smart-rice",
    irrigationMethodId: "awd",
    selectedCrops: ["Lúa ST25"],
    status: "active",
    createdAt: "2026-02-18",
  },
  {
    id: "mock-zone-dl-coffee",
    name: "Vùng cà phê hữu cơ Ea Tu",
    scope: "plot",
    targetIds: ["plot-dl-a1"],
    targetName: "Lô cà phê A1",
    enterpriseId: "ent-highland",
    certificateIds: ["Organic EU", "Rainforest Alliance"],
    managerIds: ["Y Bih Niê"],
    note: "Vùng mock đang tạm ngưng để cải tạo đất và bổ sung cây che bóng.",
    farmingMethodId: "organic",
    irrigationMethodId: "sprinkler",
    selectedCrops: ["Cà phê Robusta TRS1"],
    status: "inactive",
    createdAt: "2025-12-01",
  },
];

export const mockSearchZoneDetailRecords = {
  "mock-zone-bp-export": {
    owner: "EcoDurian Bình Phước",
    areaText: "126.8 ha",
    managers: ["Nguyễn Văn Phú", "Trần Thị Mai"],
    certifications: ["VietGAP", "GlobalGAP", "Mã vùng trồng CN-09101"],
    crops: ["Sầu riêng Ri6", "Sầu riêng Musang King"],
    irrigation: "Tưới nhỏ giọt tự động, cảm biến ẩm theo từng hàng",
    farmingMethod: "Hữu cơ kết hợp IPM",
    activePlans: ["Kế hoạch ra hoa nghịch vụ 2026", "Giám sát dư lượng trước thu hoạch"],
    devices: ["Gateway IoT BP-01", "12 cảm biến ẩm", "4 trạm thời tiết mini"],
  },
  "mock-zone-bp-area": {
    owner: "EcoDurian Bình Phước",
    areaText: "46.2 ha",
    managers: ["Lê Quốc Huy"],
    certifications: ["VietGAP", "HACCP"],
    crops: ["Sầu riêng Ri6"],
    irrigation: "Tưới nhỏ giọt phân khu A",
    farmingMethod: "VietGAP",
    activePlans: ["Theo dõi đơn hàng xuất khẩu tháng 10/2026"],
    devices: ["6 cảm biến ẩm", "Camera cổng khu A"],
  },
  "mock-zone-dt-rice": {
    owner: "Mekong Fresh",
    areaText: "88.4 ha",
    managers: ["Phạm Minh Tâm", "Võ Thị Lan"],
    certifications: ["SRP", "VietGAP", "OCOP 4 sao"],
    crops: ["Lúa ST25"],
    irrigation: "Tưới ngập khô xen kẽ AWD",
    farmingMethod: "Canh tác lúa thông minh",
    activePlans: ["Vụ Thu Đông 2026", "Giám sát đạo ôn bằng bẫy đèn"],
    devices: ["4 cảm biến mực nước", "2 bẫy đèn thông minh"],
  },
  "mock-zone-dl-coffee": {
    owner: "Highland Organic",
    areaText: "24.6 ha",
    managers: ["Y Bih Niê"],
    certifications: ["Organic EU", "Rainforest Alliance"],
    crops: ["Cà phê Robusta TRS1"],
    irrigation: "Tưới phun mưa cục bộ",
    farmingMethod: "Hữu cơ, xen canh cây che bóng",
    activePlans: ["Cải tạo đất mùa khô 2026"],
    devices: ["3 cảm biến pH đất", "1 trạm mưa"],
  },
} as const;
