import { useGeoProvinces, useGeoWards } from "@/features/master-data";
import { Button, Card, CardContent, Input, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Textarea } from "@Team-Trung-Vu-Khang/eco-shared-ui";
import { ImagePlus, MapPin, Upload } from "lucide-react";
import { useRef } from "react";
import type { CooperativeFormData } from "../types/types";

interface Props { formData: CooperativeFormData; setFormData: (data: CooperativeFormData) => void; onImageUpload: (event: React.ChangeEvent<HTMLInputElement>) => void; onComplete: () => void; isEdit?: boolean; }

export default function SimpleCooperativeForm({ formData, setFormData, onImageUpload, onComplete, isEdit = false }: Props) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const provincesQuery = useGeoProvinces({ params: { status: "active", page: 0, size: 100 } });
  const wardsQuery = useGeoWards({ params: { provinceCode: formData.province, status: "active", page: 0, size: 100 }, enabled: Boolean(formData.province) });
  const update = (patch: Partial<CooperativeFormData>) => setFormData({ ...formData, ...patch });
  const isValid = Boolean(formData.code.trim() && formData.name.trim() && formData.taxCode.trim() && formData.province.trim() && formData.district.trim() && formData.address.trim());
  return <div className="mx-auto max-w-3xl space-y-6 pb-24">
    <div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-emerald-900"><h3 className="font-semibold">Chế độ đơn giản</h3><p className="text-sm text-emerald-700">{isEdit ? "Cập nhật nhanh các thông tin cần thiết của hợp tác xã." : "Nhập nhanh các thông tin cần thiết để tạo hợp tác xã."}</p></div>
    <Card className="rounded-3xl border-slate-200 shadow-sm"><CardContent className="space-y-6 p-6">
      <div className="flex flex-col gap-4 rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-4 sm:flex-row sm:items-center"><div className="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-2xl border bg-white">{formData.image ? <img src={formData.image} alt="Logo hợp tác xã" className="h-full w-full object-contain" /> : <ImagePlus className="h-7 w-7 text-slate-300" />}</div><div className="flex-1"><Label>Logo / hình ảnh</Label><p className="mt-1 text-xs text-slate-500">JPG hoặc PNG, tối đa 5MB.</p></div><input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={onImageUpload} /><Button type="button" variant="outline" onClick={() => fileInputRef.current?.click()} className="gap-2"><Upload className="h-4 w-4" />Tải logo</Button></div>
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label required>Mã hợp tác xã</Label><Input value={formData.code} onChange={(e) => update({ code: e.target.value })} placeholder="VD: HTX001" /></div><div className="space-y-2"><Label required>Tên hợp tác xã</Label><Input value={formData.name} onChange={(e) => update({ name: e.target.value })} placeholder="Nhập tên hợp tác xã" /></div><div className="space-y-2"><Label required>Mã số thuế</Label><Input value={formData.taxCode} onChange={(e) => update({ taxCode: e.target.value })} placeholder="Nhập mã số thuế" /></div><div className="space-y-2"><Label>Số điện thoại</Label><Input value={formData.phone} onChange={(e) => update({ phone: e.target.value })} placeholder="Nhập số điện thoại" /></div></div>
      <div className="space-y-4 border-t border-slate-100 pt-5"><div className="flex items-center gap-2 text-sm font-bold text-slate-800"><MapPin className="h-4 w-4 text-emerald-600" />Địa chỉ hợp tác xã</div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label required>Tỉnh thành</Label><Select value={formData.province} onValueChange={(value) => update({ province: value, district: "" })}><SelectTrigger><SelectValue placeholder="Chọn tỉnh thành" /></SelectTrigger><SelectContent className="max-h-60 overflow-y-auto">{provincesQuery.items.map((item) => <SelectItem key={item.code} value={item.code}>{item.fullName || item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label required>Phường xã</Label><Select value={formData.district} onValueChange={(value) => update({ district: value })} disabled={!formData.province}><SelectTrigger><SelectValue placeholder="Chọn phường xã" /></SelectTrigger><SelectContent className="max-h-60 overflow-y-auto">{wardsQuery.items.map((item) => <SelectItem key={item.code} value={item.code}>{item.fullName || item.name}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-2"><Label required>Địa chỉ chi tiết</Label><Input value={formData.address} onChange={(e) => update({ address: e.target.value })} placeholder="Số nhà, đường, thôn/xóm..." /></div></div>
      <div className="space-y-2 border-t border-slate-100 pt-5"><Label>Ghi chú</Label><Textarea value={formData.description} onChange={(e) => update({ description: e.target.value })} rows={4} placeholder="Nhập ghi chú về hợp tác xã..." /></div><Button type="button" onClick={onComplete} disabled={!isValid} className="h-12 w-full rounded-xl text-base font-bold">{isEdit ? "Cập nhật hợp tác xã" : "Tạo mới hợp tác xã"}</Button>
    </CardContent></Card>
  </div>;
}
