import type { DocumentRecord, VersionFormState } from "./types";

export const INITIAL_DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc-1",
    code: "SOP-LUA-001",
    name: "Quy trình canh tác lúa hữu cơ",
    type: "Quy trình canh tác",
    scope: "Mùa vụ Xuân Hè",
    ownerRole: "Kỹ thuật viên vùng trồng",
    approverRole: "Quản lý sản xuất",
    currentVersionId: "doc-1-v2",
    versions: [
      {
        id: "doc-1-v1",
        version: "v1.0",
        effectiveFrom: "2026-01-01",
        effectiveTo: "2026-03-31",
        status: "expired",
        fileName: "quy-trinh-lua-huu-co-v1.pdf",
        changeSummary: "Ban hành quy trình chuẩn cho vụ đầu năm.",
        updatedBy: "Nguyễn Thị Lan",
        updatedAt: "2026-01-01T08:30:00",
        basedOnVersionId: null,
      },
      {
        id: "doc-1-v2",
        version: "v1.1",
        effectiveFrom: "2026-04-01",
        effectiveTo: "2026-09-30",
        status: "active",
        fileName: "quy-trinh-lua-huu-co-v1-1.pdf",
        changeSummary:
          "Điều chỉnh quy trình bón phân và lịch phun phòng sâu bệnh.",
        updatedBy: "Phạm Quốc Huy",
        updatedAt: "2026-03-28T10:30:00",
        basedOnVersionId: "doc-1-v1",
      },
      {
        id: "doc-1-v3",
        version: "v1.2",
        effectiveFrom: "2026-10-01",
        effectiveTo: "2026-12-31",
        status: "pending",
        fileName: "quy-trinh-lua-huu-co-v1-2.pdf",
        changeSummary: "Bổ sung checklist truy xuất nguồn gốc cho vụ cuối năm.",
        updatedBy: "Phạm Quốc Huy",
        updatedAt: "2026-04-19T08:10:00",
        basedOnVersionId: "doc-1-v2",
      },
    ],
    logs: [
      {
        id: "log-1",
        versionId: "doc-1-v3",
        action: "created",
        user: "Phạm Quốc Huy",
        at: "2026-04-19T08:10:00",
        detail: "tạo version v1.2 và gửi quản lý duyệt.",
      },
      {
        id: "log-2",
        versionId: "doc-1-v2",
        action: "approved",
        user: "Trần Thanh Bình",
        at: "2026-03-30T16:45:00",
        detail: "duyệt version v1.1 cho giai đoạn 01/04 - 30/09.",
      },
      {
        id: "log-3",
        versionId: "doc-1-v2",
        action: "updated",
        user: "Phạm Quốc Huy",
        at: "2026-03-28T10:30:00",
        detail: "cập nhật quy trình bón phân và phun phòng sâu bệnh.",
      },
    ],
  },
  {
    id: "doc-2",
    code: "TRACE-XG-014",
    name: "Hồ sơ truy xuất nguồn gốc xoài xuất khẩu",
    type: "Hồ sơ truy xuất",
    scope: "Đơn hàng EU",
    ownerRole: "Kỹ thuật viên hồ sơ",
    approverRole: "Quản lý chất lượng",
    currentVersionId: "doc-2-v2",
    versions: [
      {
        id: "doc-2-v1",
        version: "v2.0",
        effectiveFrom: "2025-12-01",
        effectiveTo: "2026-02-29",
        status: "expired",
        fileName: "ho-so-truy-xuat-xoai-v2-0.xlsx",
        changeSummary: "Chuẩn hóa biểu mẫu truy xuất theo lô hàng.",
        updatedBy: "Lê Minh Khang",
        updatedAt: "2025-11-25T14:20:00",
        basedOnVersionId: null,
      },
      {
        id: "doc-2-v2",
        version: "v2.1",
        effectiveFrom: "2026-03-01",
        effectiveTo: null,
        status: "active",
        fileName: "ho-so-truy-xuat-xoai-v2-1.xlsx",
        changeSummary:
          "Bổ sung mã QR đóng gói và trường thông tin lô sơ chế.",
        updatedBy: "Lê Minh Khang",
        updatedAt: "2026-02-26T09:15:00",
        basedOnVersionId: "doc-2-v1",
      },
    ],
    logs: [
      {
        id: "log-4",
        versionId: "doc-2-v2",
        action: "approved",
        user: "Ngô Thu Hà",
        at: "2026-02-28T11:00:00",
        detail: "duyệt version v2.1 cho hồ sơ xuất khẩu EU.",
      },
      {
        id: "log-5",
        versionId: "doc-2-v2",
        action: "updated",
        user: "Lê Minh Khang",
        at: "2026-02-26T09:15:00",
        detail: "cập nhật cấu trúc mã QR và thông tin lô sơ chế.",
      },
    ],
  },
  {
    id: "doc-3",
    code: "CERT-VG-003",
    name: "Tài liệu chứng nhận VietGAP vùng rau màu",
    type: "Chứng nhận",
    scope: "Vùng rau màu 12ha",
    ownerRole: "Chuyên viên chứng nhận",
    approverRole: "Trưởng bộ phận QA",
    currentVersionId: null,
    versions: [
      {
        id: "doc-3-v1",
        version: "v1.0",
        effectiveFrom: "2025-01-01",
        effectiveTo: "2025-12-31",
        status: "expired",
        fileName: "vietgap-rau-mau-v1.pdf",
        changeSummary: "Bộ tài liệu chứng nhận năm 2025.",
        updatedBy: "Võ Mỹ Linh",
        updatedAt: "2024-12-20T15:00:00",
        basedOnVersionId: null,
      },
      {
        id: "doc-3-v2",
        version: "v1.1",
        effectiveFrom: "2026-05-01",
        effectiveTo: "2027-04-30",
        status: "draft",
        fileName: "vietgap-rau-mau-v1-1.pdf",
        changeSummary: "Chuẩn bị hồ sơ tái chứng nhận năm 2026.",
        updatedBy: "Võ Mỹ Linh",
        updatedAt: "2026-04-18T13:20:00",
        basedOnVersionId: "doc-3-v1",
      },
    ],
    logs: [
      {
        id: "log-6",
        versionId: "doc-3-v2",
        action: "created",
        user: "Võ Mỹ Linh",
        at: "2026-04-18T13:20:00",
        detail: "tạo version v1.1 để chuẩn bị tái chứng nhận VietGAP.",
      },
    ],
  },
];

export const EMPTY_FORM: VersionFormState = {
  documentId: "",
  baseVersionId: "none",
  version: "",
  effectiveFrom: "",
  effectiveTo: "",
  fileName: "",
  changeSummary: "",
  status: "pending",
};
