import type { Variety } from "./types";

export const initialData: Variety[] = [
  {
    id: "1",
    illustration:
      "https://thegioicaytrong.vn/upload/img/products/20062019/76db144876d935dcb841b12608a2b5f0.jpg",
    crop: "Dừa",
    varietyCode: "COCO01",
    varietyName: "Dừa Xiêm xanh",
    scientificName: "Cocos nucifera L.",
    origin: "Đồng bằng sông Cửu Long",
    growthDuration: "2.5 - 3 năm",
    averageYield: "120 - 150 trái/cây/năm",
    description:
      "Đây là giống dừa lùn uống nước phổ biến nhất ở Đồng bằng sông Cửu Long [4, 5]. Trái có vỏ mỏng, màu xanh, thể tích từ 250-350 ml/trái với vị nước ngọt thanh đạt 7-7,5% đường [4-6].",
    seedType: "Cây giống thực sinh",
    documents: [{ name: "ky-thuat-trong-dua-xiem-xanh.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
  {
    id: "2",
    illustration:
      "https://dua.vn/wp-content/uploads/2023/08/dua-xiem-luc-vua-hai.jpg",
    crop: "Dừa",
    varietyCode: "COCO02",
    varietyName: "Dừa Xiêm lục",
    scientificName: "Cocos nucifera L.",
    origin: "Bến Tre",
    growthDuration: "18 - 24 tháng",
    averageYield: "150 - 160 trái/cây/năm",
    description:
      "Là giống dừa uống nước có chất lượng ngon nhất, ra hoa cực sớm chỉ sau 18-20 tháng trồng [7-9]. Trái có hình quả lê, nước cực ngọt (8-9% đường) và gáo dừa dày giúp ít vỡ trái khi sơ chế, vận chuyển xuất khẩu [8, 9].",
    seedType: "Cây giống thực sinh",
    documents: [{ name: "huong-dan-dua-xiem-luc.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
  {
    id: "3",
    illustration:
      "https://drinkocany.com/wp-content/uploads/2023/06/dua-sap.jpg",
    crop: "Dừa",
    varietyCode: "COCO03",
    varietyName: "Dừa sáp (Dừa kem)",
    scientificName: "Cocos nucifera L.",
    origin: "Cầu Kè, Trà Vinh",
    growthDuration: "4 - 4.5 năm",
    averageYield: "40 - 80 trái/cây/năm",
    description:
      "Thuộc nhóm dừa cao mang đột biến gen tự nhiên, nổi bật với phần cơm dừa cực dày, mềm xốp như sáp và nước sền sệt béo ngậy [10-12]. Loại dừa này mang lại giá trị kinh tế cao nhất tại Việt Nam với giá từ 110.000 đến 220.000 VNĐ/trái [13, 14].",
    seedType: "Cây giống cấy phôi / cấy mô",
    documents: [{ name: "nhan-giong-dua-sap-cay-mo.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
  {
    id: "4",
    illustration:
      "https://cayantrai.vn/wp-content/uploads/2025/03/dua-dua-2.jpg",
    crop: "Dừa",
    varietyCode: "COCO04",
    varietyName: "Dừa dứa (Dừa thơm Thái Lan)",
    scientificName: "Cocos nucifera L.",
    origin: "Thái Lan",
    growthDuration: "2.5 - 3 năm",
    averageYield: "80 - 140 trái/cây/năm",
    description:
      "Tất cả các bộ phận của cây từ lá, phấn, cơm đến nước dừa đều tỏa ra mùi thơm của lá dứa tự nhiên [13, 15, 16]. Trái càng nhỏ thì hương thơm càng đậm đà nhưng tỷ lệ nảy mầm lại càng thấp (chỉ 10-20%) [16, 17].",
    seedType: "Cây giống thực sinh",
    documents: [{ name: "ky-thuat-cham-soc-dua-dua.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
  {
    id: "5",
    illustration: "https://dua.vn/wp-content/uploads/2023/08/dua-ben-tre-1.jpg",
    crop: "Dừa",
    varietyCode: "COCO05",
    varietyName: "Dừa ta",
    scientificName: "Cocos nucifera L.",
    origin: "Bản địa Việt Nam",
    growthDuration: "4.5 - 5 năm",
    averageYield: "60 - 80 trái/cây/năm",
    description:
      "Giống dừa cao phổ biến nhất ở Việt Nam, là rường cột của ngành công nghiệp ép dầu và nạo sấy [18, 19]. Trái to, trọng lượng 1.6-2.0 kg, cơm dừa cực dày (11-13mm) và có hàm lượng dầu hảo hạng đạt 65-67% [18-20].",
    seedType: "Cây giống thực sinh",
    documents: [{ name: "tai-lieu-dua-ta.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
  {
    id: "6",
    illustration:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSorpmj4229_9TehFpU-dnF447tamnpGC0Vdg&s",
    crop: "Dừa",
    varietyCode: "COCO06",
    varietyName: "Dừa dâu",
    scientificName: "Cocos nucifera L.",
    origin: "Bản địa Việt Nam",
    growthDuration: "4 - 4.5 năm",
    averageYield: "80 - 100 trái/cây/năm",
    description:
      "Là giống dừa cao sai trái phổ biến thứ nhì tại Việt Nam, mang đặc điểm của nhóm trung gian giữa dừa cao và lùn [21, 22]. Trái có vỏ mỏng, gáo mỏng, cơm dày nên rất được ưu tiên làm mứt dừa truyền thống [20, 21, 23].",
    seedType: "Cây giống thực sinh",
    documents: [{ name: "canh-tac-dua-dau.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
  {
    id: "7",
    illustration: "https://dailyduabentre.com/upload/ckfinder/images/14.jpg",
    crop: "Dừa",
    varietyCode: "COCO07",
    varietyName: "Dừa lai PB 121",
    scientificName: "Cocos nucifera L.",
    origin: "Lai nhân tạo (Mã Lai x Tây Phi)",
    growthDuration: "2.5 - 3 năm",
    averageYield: "150 - 200 trái/cây/năm",
    description:
      "Tổ hợp lai giữa dừa lùn vàng Mã Lai và dừa cao Tây Phi, cho năng suất cực kỳ cao [24-26]. Trái có cơm dày 13-14mm, hàm lượng dầu cao 65-67% và mang khả năng thích ứng tuyệt vời với các điều kiện môi trường khắc nghiệt [24, 27].",
    seedType: "Cây giống lai nhân tạo",
    documents: [{ name: "ky-thuat-dua-lai.pdf", url: "#" }],
    status: "active",
    updatedAt: "2026-06-02",
  },
];
