import type { Variety } from "./types";

export const initialData: Variety[] = [
  {
    id: "1",
    illustration:
      "https://traicayvuongtron.vn/resources/cache/original_xxxxx/WEBSITE%202023/tim%20hieu%20them/blog/kinh%20nghiem%2Cmeo%20vat/trai%20cay/trai%20cay%20dac%20san/sauriengri6/sauriengri62.jpg.webp",
    crop: "Sầu riêng",
    varietyCode: "VARI01",
    varietyName: "Sầu riêng Ri6",
    scientificName: "Durio zibethinus",
    origin: "Việt Nam (Cái Mơn)",
    growthDuration: "4-5 năm",
    averageYield: "15-20 tấn/ha",
    description:
      "Giống sầu riêng hạt lép, cơm vàng hạt nhỏ phổ biến vùng đồng bằng sông Cửu Long và Đông Nam Bộ.",
    documents: [{ name: "huong-dan-nuoi-trong.pdf", url: "#" }],
    status: "active",
    updatedAt: "2024-01-20",
  },
  {
    id: "2",
    illustration:
      "https://nongsantaynguyen.net/wp-content/uploads/2017/04/sau-rieng-dona-sau-rieng-thai-lan.jpg",
    crop: "Sầu riêng",
    varietyCode: "VARI02",
    varietyName: "Sầu riêng Dona",
    scientificName: "Durio zibethinus (Monthong)",
    origin: "Thái Lan",
    growthDuration: "4 năm",
    averageYield: "20-25 tấn/ha",
    description:
      "Giống ngắn ngày, chịu hạn tốt, độ ngọt cao, cơm vàng dày, thơm đặc trưng.",
    seedType: "Cây giống ghép",
    documents: [{ name: "ky-thuat-cham-soc-saurieng.pdf", url: "#" }],
    status: "active",
    updatedAt: "2024-01-21",
  },
  {
    id: "3",
    illustration:
      "https://cdn2.fptshop.com.vn/unsafe/1920x0/filters:format(webp):quality(75)/sau_Musa_King_01_0ea1377077.jpg",
    crop: "Sầu riêng",
    varietyCode: "VARI03",
    varietyName: "Sầu riêng Musang King",
    scientificName: "Durio zibethinus (D197)",
    origin: "Malaysia",
    growthDuration: "4-5 năm",
    averageYield: "10-14 tấn/ha",
    description:
      "Vỏ xanh, cơm vàng đậm, vị béo ngậy như bơ. Hạt lép hoàn toàn.",
    seedType: "Cây giống ghép cao cấp",
    documents: [],
    status: "active",
    updatedAt: "2024-01-22",
  },
  {
    id: "4",
    illustration:
      "https://vinadurian.com/wp-content/uploads/2023/11/sau-rieng-black-thorn-05-i.jpg",
    crop: "Sầu riêng",
    varietyCode: "VARI04",
    varietyName: "Sầu riêng Black Thorn",
    scientificName: "Durio zibethinus (Ochee)",
    origin: "Malaysia",
    growthDuration: "4-5 năm",
    averageYield: "12-16 tấn/ha",
    description: "Năng suất cao, kháng bệnh tốt, chất lượng trái thượng hạng.",
    seedType: "Hạt giống F1",
    documents: [{ name: "quy-trinh-canh-tac-saurieng.pdf", url: "#" }],
    status: "active",
    updatedAt: "2024-01-23",
  },
  {
    id: "5",
    illustration:
      "https://lh4.googleusercontent.com/proxy/MLacA6_LHyfmPvTfcrouV2QTLptGspn7YeqqJ9pAjtfQIl262TRrvqXI5nMWlZuSLoOKCs3pwfShUOALa0aEKTu8ATDBIrKX07oDdVXW6fdSHTlsi6vflJMhwO5QILIl3Dz5GLaveQ",
    crop: "Lúa",
    varietyCode: "VARI06",
    varietyName: "Lúa OM5451",
    scientificName: "Oryza sativa",
    origin: "Việt Nam (Viện Lúa ĐBSCL)",
    growthDuration: "90-95 ngày",
    averageYield: "6-8 tấn/ha",
    description: "Giống lúa ngắn ngày, năng suất ổn định, cơm mềm thơm.",
    documents: [{ name: "ky-thuat-lua-om5451.pdf", url: "#" }],
    status: "active",
    updatedAt: "2024-01-20",
  },
  {
    id: "6",
    illustration:
      "https://truyenthongkhoahoc.vn/photos/1/Tuan%20sau%202/dt84-min.jpg",
    crop: "Đậu nành",
    varietyCode: "VARI07",
    varietyName: "Đậu nành DT84",
    scientificName: "Glycine max (DT84)",
    origin: "Việt Nam (Viện Di truyền nông nghiệp)",
    growthDuration: "85-95 ngày",
    averageYield: "1.5-2.5 tấn/ha",
    description: "Khả năng chịu hạn tốt, quả chắc, hàm lượng protein cao.",
    documents: [],
    status: "active",
    updatedAt: "2024-02-15",
  },
  {
    id: "7",
    illustration: "https://vafs.gov.vn/wp-content/uploads/2018/01/2-3.jpg",
    crop: "Đậu nành",
    varietyCode: "VARI08",
    varietyName: "Đậu nành DX11",
    scientificName: "Glycine max (DX11)",
    origin: "Việt Nam",
    growthDuration: "90-100 ngày",
    averageYield: "1.8-2.8 tấn/ha",
    description: "Giống dài ngày, hạt to, đồng đều, phù hợp xen canh.",
    documents: [],
    status: "active",
    updatedAt: "2024-02-16",
  },
];
